(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 1024,
	height: 768,
	fps: 12,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



(lib.numboxlvl_grey = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EAEAEA").s().p("Ag7FVIAAqpIB2AAIAAKpg");
	this.shape.setTransform(6,34.2);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,12,68.3);


(lib.mcWarning = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("A09BVQgIgCgFgEQgGgFgFgGQgEgGgCgJIAOAAIAHAKQADADAFADIAIADIAJABIAJgBIAGgDQAGgDADgIQAEgFABgJIABgQIgGAHIgHADQgFACgEABIgJABIgLgBIgJgDQgKgFgEgEIgGgHIgEgHIgDgIIgBgHQAAgHAEgMQACgFAHgKIAHgFIAIgEIAJgCIAJgBIAKAAIAIADIAIAEIAHAGIAAgNIAQAAIAABGQgBAUgBAIIgEALQgCAFgCAEQgKAIgGADIgJAEIgLABQgIAAgIgDgA08geQgFACgFAEQgDAEgDAGQgCAGAAAHQAAAFACAGQACAFAFAEQAEAFAGACQAGADAHgBQAGABAGgDQAFgDAFgEQAEgEADgGQACgGAAgFQAAgGgCgGQgDgGgFgEQgEgEgFgCQgGgCgHgBQgGABgHACgEAqzAAqIAAgVIARAAIAAAVgEApvAAqIAAhZIAPAAIAAALQAEgFAGgDQAFgDAIAAQAFAAAFACIAAAQIgEgCIgBgBIgFAAQgFABgFABQgDADgEADIgEAIQgCAFAAAFIAAAwgEAokAAoIgJgCQgMgGgDgEIgHgHIgEgHIgDgIIgBgIIABgJIADgIQACgGAIgJIAPgJIAJgDIAUAAIAJADIAIAEIAGAFIAGAIQADAEABAFIADAKIABAJIhPAAQABAFACAFQADAEAFAEQAEAEAFACQAGACAGgBQAIAAAGgCQAHgDAEgFIATAAIgIAKQgFAFgGADQgFADgHABQgGACgGABgEApMgAKQgCgFgCgEIgHgHIgJgFIgLgBQgGAAgFABQgFACgEADIgHAHQgDAEgBAFIA+AAIAAAAgEAmvAAmIgIgEIgHgGIAAAOIgPAAIAAiBIAPAAIAAA1IAHgGIAIgEQAFgCANgBQAHAAAMAEQAFACAKAHQAIAJACAGIADAIIABAJIgBAIIgCAIIgFAIIgGAGQgJAIgGACQgNAEgGAAQgNgCgFgCgEAmzgAeQgFADgFADQgFAFgCAFQgDAGABAHQgBADADAHQACAFAFAEQAFAFAFADQAHACAHAAQAHAAAFgCQAGgDAEgEQAFgFADgFQACgGAAgEQAAgHgCgGQgDgGgEgEQgFgDgGgDQgFgCgHgBQgHABgHACgEAlxAAqIAAgxQAAgHgBgFQgCgFgDgDQgCgDgFgCQgDgBgGAAQgFAAgDABQgEACgDADQgDADgCAFQgCAFABAHIAAAxIgQAAIAAgyQAAgGgBgFQgCgFgEgDQgCgDgEgCIgJgBQgFABgEABQgEACgDADQgCADgCAFQgCAEAAAGIAAAyIgPAAIAAhYIAPAAIAAAHQAFgEAFgCQAGgCAIAAIAIABIAIADIAGAEIAGAGIAGgGIAIgEIAIgDIAKAAQAHAAAGACQAIACAEAFQAEAEADAIQACAHAAAKIAAAygEAjVAAqIAAgLQgEAFgHADQgGADgIAAQgKAAgGgDQgIgCgFgGQgFgEgDgJQgCgFgBgNIAAgvIAQAAIAAAvQAAAGABAGQACAGAEADQADADAEACQAEABAHAAQAFAAAFgBQAEgCAEgEQADgEABgFQACgGAAgGIAAguIAQAAIAABZgEAhxAAqIAAgtQAAgIgCgGQgCgFgDgEQgDgDgFgCQgFgBgFgBQgGABgFABQgEACgDADQgDAEgCAFQgCAFAAAHIAAAvIgQAAIAAhYIAQAAIAAAJQAGgFAGgCQAGgDAJAAQAIAAAHADQAHACAGAGQAFAFADAIQACANABAHIAAAtgAfAAqIAAhZIAPAAIAAALQAEgFAFgDQAHgDAHAAQAFAAAGACIAAAQIgFgCIgCgBIgEAAQgFABgEABQgFADgDADIgFAIQgBAFAAAFIAAAwgAd0AoIgJgCQgLgGgDgEIgGgHIgFgHIgDgIIgBgIIABgJIADgIQACgGAIgJIAPgJIAJgDIATAAIAJADIAIAEIAIAFIAFAIQADAEABAFIADAKIABAJIhOAAQAAAFACAFQADAEAFAEQAEAEAGACQAFACAGgBQAHAAAHgCQAGgDAFgFIATAAIgIAKQgFAFgGADQgFADgGABQgHACgHABgAedgKQgCgFgDgEIgHgHIgJgFIgLgBQgFAAgFABQgFACgEADIgHAHQgDAEgBAFIA+AAIAAAAgAcxAqIAAguQAAgHgDgGQgBgFgDgDQgEgEgFgCQgEgBgFgBQgGABgEABQgFACgDADQgEAEgCAFQgCAFAAAHIAAAvIgPAAIAAiBIAPAAIAAAyQAFgFAHgCQAGgCAJAAQAIAAAIACQAHADAFAFQAFAFADAIQADAMAAAHIAAAugAbLAqQgGAAgFgEQgEgCgBgEQgDgFAAgHIAAg0IgQAAIAAgOIAQAAIAAgpIAQAAIAAApIAUAAIAAAOIgUAAIAAA1QAAABABAAQAAABAAAAQAAABABAAQAAABABAAIAGABQAIgBADgEIAAAPQgHAFgGABgAXMAoIgJgCQgKgGgFgEIgFgHIgFgHIgDgIIAAgIIAAgJIADgIQACgGAIgJIAPgJIAJgDIATAAIAJADIAIAEIAIAFIAFAIQADAEACAFIACAKIABAJIhOAAQAAAFACAFQADAEAFAEQAEAEAGACQAFACAGgBQAHAAAHgCQAHgDAEgFIATAAIgIAKQgFAFgGADQgFADgGABQgHACgHABgAX1gKQgCgFgDgEIgHgHIgJgFIgLgBQgFAAgFABQgFACgEADIgHAHQgDAEgBAFIA+AAIAAAAgAWJAqIAAguQgBgHgCgGQgBgFgDgDQgEgEgEgCQgFgBgFgBQgGABgEABQgFACgDADQgEAEgCAFQgCAFABAHIAAAvIgQAAIAAiBIAQAAIAAAyQAEgFAHgCQAGgCAJAAQAJAAAHACQAHADAFAFQAFAFADAIQADAMAAAHIAAAugAUjAqQgGAAgFgEQgEgCgBgEQgCgFgBgHIAAg0IgQAAIAAgOIAQAAIAAgpIARAAIAAApIATAAIAAAOIgTAAIAAA1QAAABAAAAQAAABAAAAQAAABABAAQAAABABAAIAGABQAHgBAEgEIAAAPQgGAFgHABgAS1AqIAAgtQAAgIgBgGQgCgFgEgEQgCgDgGgCQgEgBgGgBQgFABgFABQgEACgEADQgDAEgBAFQgCAFAAAHIAAAvIgQAAIAAhYIAQAAIAAAJQAFgFAHgCQAGgDAIAAQAJAAAGADQAIACAFAGQAGAFADAIQACANAAAHIAAAtgAROAqIAAgOIgGAGIgIAEQgEACgEAAIgKACQgNgCgGgCQgLgFgFgEIgFgGIgFgHIgCgJIgBgHIABgKIACgJQADgFAHgKIAIgFIAIgEIAJgDIATAAIAJADIAIADIAGAGIAAgMIAQAAIAABYgAQhgeQgFADgFADQgEAFgDAFQgDAHAAAGQAAAEADAGQADAGAEADQAEAFAHACQAGACAGAAQAHAAAGgCQAFgCAFgFQAEgDACgGQADgGAAgEQAAgHgDgGQgCgFgEgFQgEgDgHgDQgGgCgGgBQgHABgGACgAPhAqIAAguQAAgHgCgGQgCgFgDgDQgDgEgFgCQgEgBgGgBQgGABgEABQgFACgDADQgDAEgCAFQgCAFAAAHIAAAvIgQAAIAAiBIAQAAIAAAyQAFgFAGgCQAHgCAIAAQAJAAAHACQAIADAFAFQAFAFADAIQACAMAAAHIAAAugAN8AqQgHAAgFgEQgDgCgCgEQgCgFAAgHIAAg0IgRAAIAAgOIARAAIAAgpIAQAAIAAApIATAAIAAAOIgTAAIAAA1QAAABAAAAQAAABABAAQAAABAAAAQABABAAAAIAHABQAHgBADgEIAAAPQgGAFgGABgALrAnQgHgCgGgDQgFgEgDgGQgDgFAAgIIARAAQABAFACACQABADADADIAHADIAJAAQAIAAAHgCQACgCACgDQACgCAAgCQAAgEgGgDIgigJIgHgEQgFgDgDgFQgCgEABgGQAAgFACgFQADgEAEgEQAFgDAGgCQAHgCAIAAQAHAAAGACQAHACAFADQAFAEACAEQADAFAAAGIgSAAQAAgDgBgCIgFgFQgFgDgGAAIgJAAIgHADQgDAEAAAEQAAAEACADQAEADAKAEIAVAFQAJACAEADIAFAGIACAHQABAGgDAFQgDAFgFAEQgGADgGACQgIACgIABQgJgBgHgCgAKPAnQgIgCgGgDQgEgEgDgGQgEgFAAgIIASAAQAAAFACACQABADAEADIAHADIAJAAQAHAAAHgCQADgCACgDQABgCAAgCQAAgEgGgDIghgJIgHgEQgFgDgDgFQgCgEAAgGQAAgFADgFQACgEAFgEQAFgDAGgCQAHgCAHAAQAIAAAGACQAGACAFADQAFAEACAEQADAFABAGIgSAAQAAgDgCgCIgEgFQgFgDgHAAIgJAAIgGADQgEAEAAAEQAAAEADADQAEADAJAEIAWAFQAIACAFADIAFAGIACAHQAAAGgDAFQgDAFgEAEQgGADgHACQgIACgHABQgKgBgGgCgAIwAoIgJgCQgLgGgEgEIgGgHIgEgHIgEgIIAAgIIAAgJIAEgIQACgGAIgJIAOgJIAJgDIAUAAIAJADIAIAEIAHAFIAGAIQADAEABAFIADAKIABAJIhPAAQAAAFADAFQADAEAEAEQAEAEAGACQAFACAGgBQAIAAAGgCQAHgDAEgFIATAAIgIAKQgFAFgFADQgGADgGABQgHACgGABgAJZgKQgCgFgDgEIgHgHIgJgFIgLgBQgGAAgFABQgFACgEADIgHAHQgDAEgBAFIA/AAIAAAAgAHoAqIAAiBIAQAAIAACBgAFwAoIgJgCQgKgGgFgEIgFgHIgFgHIgDgIIAAgIIAAgJIADgIQACgGAIgJIAPgJIAJgDIATAAIAJADIAIAEIAIAFIAFAIQADAEABAFIADAKIABAJIhOAAQAAAFACAFQADAEAFAEQAEAEAGACQAFACAGgBQAHAAAHgCQAHgDAEgFIATAAIgIAKQgFAFgGADQgFADgGABQgHACgHABgAGZgKQgCgFgDgEIgHgHIgJgFIgLgBQgFAAgFABQgFACgEADIgHAHQgDAEgBAFIA+AAIAAAAgAD7AmIgHgEIgGgGIAAAOIgQAAIAAiBIAQAAIAAA1IAGgGIAHgEQAGgCANgBQAGAAAMAEQAHACAJAHQAIAJACAGIADAIIABAJIgBAIIgDAIIgEAIIgGAGQgJAIgGACQgMAEgIAAQgMgCgGgCgAEBgeQgHADgEADQgFAFgCAFQgDAGAAAHQAAADADAHQACAFAFAEQAFAFAGADQAGACAGAAQAIAAAGgCQAFgDAFgEQAEgFACgFQADgGAAgEQAAgHgDgGQgCgGgEgEQgEgDgGgDQgGgCgIgBQgGABgGACgACRAqQgHAAgFgEQgDgCgCgEQgCgFAAgHIAAg0IgRAAIAAgOIARAAIAAgpIAQAAIAAApIATAAIAAAOIgTAAIAAA1QAAABAAAAQAAABABAAQAAABAAAAQABABAAAAIAHABQAHgBADgEIAAAPQgGAFgGABgAAsAnQgHgCgFgDQgGgEgCgGQgDgFgBgIIASAAQAAAFACACQABADAEADIAHADIAJAAQAHAAAHgCQADgCABgDQACgCAAgCQAAgEgGgDIghgJIgIgEQgEgDgDgFQgCgEAAgGQAAgFACgFQADgEAFgEQAFgDAGgCQAHgCAHAAQAHAAAHACQAGACAGADQAEAEACAEQAEAFAAAGIgSAAQgBgDgBgCIgEgFQgFgDgHAAIgJAAIgGADQgEAEAAAEQAAAEADADQAEADAJAEIAWAFQAIACAFADIAFAGIABAHQABAGgDAFQgDAFgFAEQgFADgHACQgIACgHABQgJgBgIgCgAgLAqIAAgLQgFAFgGADQgGADgJAAQgJAAgHgDQgIgCgEgGQgGgEgCgJQgCgFgBgNIAAgvIAPAAIAAAvQABAGABAGQABAGAEADQADADAFACQAEABAGAAQAFAAAFgBQAEgCAEgEQAEgEABgFQACgGAAgGIAAguIANAAIAABZgAhvAqIAAgxQAAgHgCgFQgBgFgDgDQgDgDgEgCQgDgBgGAAQgEAAgEABQgFACgCADQgDADgCAFQgCAFABAHIAAAxIgQAAIAAgyQAAgGgBgFQgCgFgEgDQgCgDgEgCIgJgBQgFABgEABQgEACgCADQgDADgCAFQgBAEgBAGIAAAyIgPAAIAAhYIAPAAIAAAHQAFgEAFgCQAGgCAIAAIAIABIAIADIAGAEIAGAGIAGgGIAHgEIAJgDIAJAAQAIAAAGACQAHACAFAFQAEAEADAIQACAHAAAKIAAAygAk1AqIAAgOIgHAGIgHAEIgJACIgJACIgKgCIgJgCQgMgGgFgEIgGgGIgEgHIgCgJIgBgHIABgKIACgIQADgGAHgJQAEgEAMgFIAJgDIAKgBQAJAAAJADIAIAEIAHAFIAAg0IAPAAIAACBgAljgeQgGADgFADQgEAEgCAGQgDAGAAAGQAAAEADAHQADAFAEAEQAEAFAHACQAFACAHAAQAHAAAGgCQAGgDAFgEQAEgEACgFQADgHAAgEQAAgGgDgGQgDgGgEgEQgEgDgHgDQgGgCgGAAQgHAAgGACgAnMAoIgJgCQgLgGgEgEIgGgHIgFgHIgCgIIgBgIIABgJIACgIQADgGAHgJIAQgJIAJgDIATAAIAJADIAIAEIAHAFIAFAIQADAEACAFIACAKIABAJIhOAAQABAFACAFQADAEAFAEQAEAEAFACQAGACAGgBQAHAAAGgCQAHgDAFgFIATAAIgIAKQgFAFgGADQgGADgGABQgHACgGABgAmkgKQgBgFgDgEIgHgHIgJgFIgLgBQgFAAgFABQgGACgDADIgHAHQgDAEgCAFIA+AAIAAAAgAoSAqQgHAAgEgEQgEgCgCgEQgCgFAAgHIAAg0IgRAAIAAgOIARAAIAAgpIAQAAIAAApIAUAAIAAAOIgUAAIAAA1QAAABAAAAQAAABABAAQAAABAAAAQABABAAAAIAHABQAHgBAEgEIAAAPQgHAFgHABgAp2AoIgKgCQgLgGgFgEIgGgGIgEgIIgDgIIgBgIIABgJIADgIQACgGAIgJQAEgDAMgGIAJgDIAKAAQAHAAAIACQAHACAGADQAFAEAFAGQAFAFADAIIgRAAIgGgIIgGgEIgIgEIgJgBQgHAAgHACQgFADgFAEQgEAEgCAGQgDAGAAAHQAAAEADAGQACAFAEAEQAFAFAGACQAGACAHAAIAIAAQAEgBAEgCQAEgCAJgLIARAAQgEAJgFAGQgFAFgGAEQgGAEgGABQgGACgIAAgAq+AqIAAgOIgGAGIgIAEQgDACgEAAIgKACQgNgCgHgCQgKgFgFgEIgGgGIgFgHIgCgJIgBgHIABgKIACgJQADgFAIgKIAHgFIAIgEIAJgDIAUAAIAIADIAIADIAGAGIAAgMIARAAIAABYgArrgeQgFADgEADQgFAFgDAFQgCAHAAAGQAAAEACAGQADAGAFADQAEAFAGACQAGACAHAAQAGAAAHgCQAFgCAEgFQAFgDACgGQACgGAAgEQAAgHgCgGQgDgFgEgFQgEgDgGgDQgGgCgHgBQgHABgGACgAtLAqIAAhZIAQAAIAAALQAEgFAFgDQAHgDAHAAQAEAAAHACIAAAQIgFgCIgCgBIgEAAQgFABgEABQgFADgCADIgGAIQgBAFAAAFIAAAwgAtxAqQgGAAgFgEQgDgCgCgEQgCgFgBgHIAAg0IgQAAIAAgOIAQAAIAAgpIARAAIAAApIATAAIAAAOIgTAAIAAA1QAAABAAAAQAAABAAAAQAAABABAAQAAABABAAIAGABQAIgBADgEIAAAPQgHAFgGABgAvhAmIgHgEIgHgGIAAAOIgQAAIAAiBIAQAAIAAA1IAHgGIAHgEQAGgCANgBQAGAAAMAEQAGACAJAHQAIAJADAGIADAIIAAAJIAAAIIgDAIIgFAIIgGAGQgJAIgFACQgNAEgHAAQgMgCgGgCgAvcgeQgGADgEADQgFAFgDAFQgCAGAAAHQAAADACAHQADAFAFAEQAEAFAGADQAHACAGAAQAHAAAGgCQAFgDAFgEQAEgFADgFQADgGgBgEQABgHgDgGQgCgGgFgEQgEgDgGgDQgGgCgHgBQgGABgHACgAwfAqIAAgLQgFAFgGADQgGADgJAAQgJAAgHgDQgIgCgEgGQgGgEgCgJQgCgFgBgNIAAgvIAPAAIAAAvQABAGABAGQABAGAEADQADADAFACQAEABAGAAQAFAAAFgBQAEgCAEgEQAEgEABgFQACgGAAgGIAAguIAPAAIAABZgAymAnQgIgCgGgDQgEgEgEgGQgDgFAAgIIASAAQAAAFACACQACADADADIAHADIAIAAQAIAAAHgCQADgCACgDQACgCAAgCQgBgEgGgDIgigJIgGgEQgFgDgDgFQgCgEAAgGQAAgFADgFQACgEAFgEQAFgDAGgCQAHgCAHAAQAHAAAHACQAHACAEADQAFAEACAEQADAFAAAGIgSAAQAAgDgBgCIgEgFQgFgDgHAAIgJAAIgGADQgEAEAAAEQAAAEADADQAEADAJAEIAVAFQAJACAFADIAEAGIADAHQAAAGgDAFQgCAFgFAEQgGADgHACQgIACgIABQgIgBgHgCgA1/AqIAAgtQAAgIgCgGQgBgFgEgEQgDgDgFgCQgEgBgGgBQgGABgEABQgFACgDADQgDAEgCAFQgCAFAAAHIAAAvIgQAAIAAhYIAQAAIAAAJQAFgFAHgCQAGgDAIAAQAJAAAHADQAIACAEAGQAGAFADAIQACANAAAHIAAAtgA3oAqIAAhYIAQAAIAABYgA41AoIgJgCQgLgGgEgEIgGgHIgEgHIgEgIIAAgIIAAgJIAEgIQACgGAIgJIAOgJIAJgDIAUAAIAJADIAIAEIAHAFIAGAIQADAEABAFIADAKIABAJIhPAAQABAFACAFQADAEAEAEQAEAEAGACQAFACAGgBQAIAAAGgCQAHgDAEgFIATAAIgIAKQgFAFgFADQgGADgGABQgHACgGABgA4MgKQgCgFgDgEIgHgHIgJgFIgLgBQgGAAgFABQgEACgFADIgHAHQgDAEgBAFIA/AAIAAAAgA6qAmIgHgEIgHgGIAAAOIgQAAIAAiBIAQAAIAAA1IAHgGIAHgEQAFgCANgBQAHAAAMAEQAGACAJAHQAJAJABAGIAEAIIABAJIgBAIIgDAIIgEAIIgHAGQgJAIgFACQgNAEgHAAQgNgCgFgCgA6lgeQgGADgEADQgFAFgDAFQgCAGAAAHQAAADACAHQADAFAFAEQAEAFAGADQAGACAHAAQAHAAAGgCQAGgDAEgEQAFgFACgFQACgGAAgEQAAgHgCgGQgDgGgEgEQgEgDgGgDQgGgCgHgBQgHABgGACgA8zAqIAAhZIAQAAIAAALQAEgFAGgDQAFgDAIAAQAEAAAHACIAAAQIgFgCIgCgBIgEAAQgFABgFABQgEADgCADIgGAIQgBAFAAAFIAAAwgA99AoIgJgCQgLgGgFgEIgFgHIgFgHIgDgIIAAgIIAAgJIADgIQACgGAIgJIAPgJIAJgDIATAAIAJADIAJAEIAHAFIAFAIQADAEACAFIACAKIABAJIhPAAQABAFADAFQADAEAEAEQAEAEAGACQAFACAGgBQAIAAAGgCQAGgDAFgFIATAAIgIAKQgFAFgFADQgHADgGABQgGACgGABgA9VgKQgBgFgDgEIgIgHIgJgFIgKgBQgGAAgFABQgFACgEADIgHAHQgDAEgBAFIA+AAIAAAAgA/yAmIgIgEIgHgGIAAAOIgPAAIAAiBIAPAAIAAA1IAHgGIAIgEQAFgCANgBQAHAAAMAEQAGACAJAHQAIAJACAGIADAIIABAJIgBAIIgCAIIgFAIIgGAGQgJAIgGACQgNAEgGAAQgNgCgFgCgA/ugeQgGADgEADQgFAFgCAFQgCAGgBAHQABADACAHQACAFAFAEQAFAFAFADQAHACAHAAQAGAAAGgCQAGgDAEgEQAFgFACgFQADgGAAgEQAAgHgDgGQgCgGgEgEQgEgDgHgDQgGgCgGgBQgHABgHACgEggwAAqIAAgxQAAgHgBgFQgCgFgDgDQgDgDgDgCQgFgBgEAAQgGAAgDABQgEACgDADQgDADgCAFQgBAFgBAHIAAAxIgPAAIAAgyQAAgGgCgFQgCgFgCgDQgDgDgEgCIgJgBQgFABgEABQgEACgDADQgDADgBAFQgBAEAAAGIAAAyIgQAAIAAhYIAQAAIAAAHQAEgEAGgCQAFgCAHAAIAJABIAIADIAHAEIAFAGIAGgGIAIgEIAIgDIAKAAQAHAAAGACQAIACAEAFQAFAEACAIQACAHABAKIAAAygEgjLAAqIAAgLQgFAFgGADQgHADgIAAQgJAAgIgDQgHgCgFgGQgFgEgDgJQgCgFAAgNIAAgvIAPAAIAAAvQAAAGABAGQACAGAEADQACADAFACQAFABAFAAQAGAAAEgBQAFgCADgEQAEgEACgFQACgGAAgGIAAguIAPAAIAABZgEgkwAAqIAAgtQAAgIgCgGQgBgFgEgEQgDgDgFgCQgEgBgGgBQgGABgEABQgFACgDADQgDAEgCAFQgCAFAAAHIAAAvIgQAAIAAhYIAQAAIAAAJQAFgFAHgCQAGgDAIAAQAJAAAHADQAIACAEAGQAGAFADAIQACANAAAHIAAAtgEgnpAAoIgJgCQgKgGgFgEIgFgHIgFgHIgDgIIAAgIIAAgJIADgIQACgGAIgJIAPgJIAJgDIATAAIAJADIAIAEIAIAFIAFAIQADAEABAFIADAKIABAJIhOAAQAAAFADAFQACAEAFAEQAEAEAGACQAFACAGgBQAHAAAHgCQAHgDAEgFIATAAIgIAKQgFAFgGADQgFADgGABQgHACgHABgEgnAgAKQgCgFgDgEIgHgHIgJgFIgLgBQgFAAgFABQgFACgEADIgHAHQgDAEgBAFIA+AAIAAAAgEgosAAqIAAguQgBgHgCgGQgBgFgDgDQgEgEgEgCQgFgBgFgBQgGABgEABQgFACgDADQgEAEgCAFQgCAFAAAHIAAAvIgPAAIAAiBIAPAAIAAAyQAFgFAHgCQAGgCAJAAQAJAAAHACQAHADAFAFQAFAFADAIQADAMAAAHIAAAugEgqoAAqIAAhxIgbAAIAAgQIBGAAIAAAQIgbAAIAABxgAZkAoIgJgCIgJgEIgHgGIgFgHIgFgHIgCgIIgBgJIABgJIACgIQADgFAHgJQAFgEALgFIAJgDIAJAAQAIAAALADQAGACAKAHQAHAJADAGIACAIIABAKIgBAHIgCAIIgFAIIgFAGQgKAHgFADQgMADgHAAgAZggeQgGADgEADQgEAEgCAGQgCAGgBAGQAAAEADAHQACAFAEAEQAFAEAGADQAGACAHAAQAGAAAGgCQAGgCAFgFQADgDACgGQADgGAAgEQAAgHgDgGQgCgGgFgEQgEgDgGgDQgGgCgGAAQgIAAgFACgA3ohEIAAgTIAQAAIAAATg");
	this.shape.setTransform(277.3,17);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(1.7,8.2,551.3,17.6);


(lib.mcValueChange_Thousands = function() {
	this.initialize();

	// Layer 1
	this.tfText_0 = new cjs.Text("", "16px 'AMCE Basic'", "#FF0000");
	this.tfText_0.name = "tfText_0";
	this.tfText_0.lineHeight = 18;
	this.tfText_0.lineWidth = 22;
	this.tfText_0.setTransform(3.2,3.5);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FF0000").ss(1,1,1).p("Aisi5IFZFz");
	this.shape.setTransform(15.1,48.2);

	this.addChild(this.shape,this.tfText_0);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-3.2,3.5,36.8,64.4);


(lib.mcValueChange_Tens = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FF0000").ss(1,1,1).p("Aisi5IFZFz");
	this.shape.setTransform(15.1,48.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FF0000").ss(1,1,1).p("Ahrk2IDzEdAisg8IFZFz");
	this.shape_1.setTransform(15.1,35.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).wait(1));

	// Layer 1
	this.tfText_1 = new cjs.Text("", "16px 'AMCE Basic'", "#FF0000");
	this.tfText_1.name = "tfText_1";
	this.tfText_1.lineHeight = 18;
	this.tfText_1.lineWidth = 22;
	this.tfText_1.setTransform(3.2,-19.1);

	this.tfText_0 = new cjs.Text("", "16px 'AMCE Basic'", "#FF0000");
	this.tfText_0.name = "tfText_0";
	this.tfText_0.lineHeight = 18;
	this.tfText_0.lineWidth = 22;
	this.tfText_0.setTransform(3.2,3.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.tfText_0},{t:this.tfText_1}]}).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-3.2,-19.1,36.8,86.9);


(lib.mcValueChange_Ones = function() {
	this.initialize();

	// Layer 1
	this.tfText_0 = new cjs.Text("", "16px 'AMCE Basic'", "#FF0000");
	this.tfText_0.name = "tfText_0";
	this.tfText_0.lineHeight = 18;
	this.tfText_0.lineWidth = 26;
	this.tfText_0.setTransform(3.2,4.5);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FF0000").ss(1,1,1).p("AivjDIFfGH");
	this.shape.setTransform(17.6,49.2);

	this.addChild(this.shape,this.tfText_0);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-1,4.5,37.3,65.4);


(lib.mcValueChange_Hundreds = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.tfText_1 = new cjs.Text("", "16px 'AMCE Basic'", "#FF0000");
	this.tfText_1.name = "tfText_1";
	this.tfText_1.lineHeight = 18;
	this.tfText_1.lineWidth = 22;
	this.tfText_1.setTransform(3.2,-19.1);

	this.tfText_0 = new cjs.Text("", "16px 'AMCE Basic'", "#FF0000");
	this.tfText_0.name = "tfText_0";
	this.tfText_0.lineHeight = 18;
	this.tfText_0.lineWidth = 22;
	this.tfText_0.setTransform(3.2,3.5);

	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#FF0000").ss(1,1,1).p("Aisi5IFZFz");
	this.shape.setTransform(15.1,48.2);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f().s("#FF0000").ss(1,1,1).p("Ahtk2IDxEaAisg7IFZFy");
	this.shape_1.setTransform(15.1,35.7);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape},{t:this.tfText_0},{t:this.tfText_1}]}).to({state:[{t:this.shape_1},{t:this.tfText_0},{t:this.tfText_1}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-3.2,-19.1,36.8,86.9);


(lib.mcLeftPanel = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#CCCCCC").s().p("AypXIMAAAguPMAlTAAAMAAAAuPg");
	this.shape.setTransform(119.5,148);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,238.9,296.1);


(lib.mcDecimal = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgJAMIAAgXIATAAIAAAXg");
	this.shape.setTransform(10,24.8);

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.004)").s().p("AhjC9IAAl6IDGAAIAAF6g");
	this.shape_1.setTransform(10,19);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,20,38);


(lib.mcArrow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF9900").s().p("AgnhVIBPBVIhPBVg");
	this.shape.setTransform(10.8,16);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#00FFFF").s().p("AgnhVIBPBVIhPBVg");
	this.shape_1.setTransform(10.8,16);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#993333").s().p("AgnhVIBPBVIhPBVg");
	this.shape_2.setTransform(10.8,16);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#EAEAEA").s().p("AgnhVIBPBVIhPBVg");
	this.shape_3.setTransform(10.8,16);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

	// Layer 3
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhoCgIAAk/IDQAAIAAE/g");
	this.shape_4.setTransform(10.5,16);

	this.timeline.addTween(cjs.Tween.get(this.shape_4).wait(4));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,21,32);


(lib.ico_plus = function() {
	this.initialize();

	// hit
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF9900").s().p("Ag6ASIAAgiIB1AAIAAAig");
	this.shape.setTransform(-0.8,-0.7);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-6.8,-2.5,12,3.6);


(lib.numdotlvl_yellow = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAVASIAAgcIgGAAIAAgEIADAAIABgBIACgCIAEAAIAAAjgAAEASIAAgFIAFAAIAAAFgAgTARQgDgCgBgDQgBgDAAgFIAAgIIABgHQABgDADgCQADgBADAAQAEAAADABQACACACADQABADAAAEIAAAIQAAAIgDADQgDADgFAAQgEAAgDgBgAgIANIACgDIABgGIAAgHIgBgFQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBIgFgBIgEABQAAAAAAABQgBAAAAAAQAAABgBAAQAAABAAAAIgBAGIAAAHIABAGQAAAAAAABQABAAAAABQAAAAABABQAAAAABAAQAAAAABABQAAAAAAAAQABAAABAAQAAAAABAAIAEgBg");
	this.shape.setTransform(-0.2,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D36240").s().p("AAAA5QgWAAgSgRQgQgRAAgXQAAgWAQgSQASgQAWAAQAXAAARAQQARASAAAWQAAAXgRARQgRARgXAAIAAAAgAASgQIgCABIgCABIAAAEIAFAAIAAAcIAFAAIAAgjIgFAAIgBABgAACASIAFAAIAAgGIgFAAgAgUgQQgEABgBAEIgBAHIAAAIQAAAFABADQABADAEACQACABAEAAQAFAAADgDQADgEABgHIAAgIQAAgEgCgDQgBgEgDgBQgDgCgEABQgDgBgCACgAgOAOQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQgBgBAAgBIgBgGIAAgGIABgGQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIADgBIAFABQAAAAABABQAAAAABABQAAAAAAABQAAAAABABIAAAFIAAAGIAAAGIgDAEIgDABIgBAAg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#982E0F").s().p("AgrAsQgSgSAAgaQAAgZASgSQASgSAZAAQAaAAASASQASASAAAZQAAAagSASQgSASgaAAQgZAAgSgSgAgogoQgQASAAAWQAAAXAQARQASARAWAAQAXAAARgRQARgRAAgXQAAgWgRgSQgRgQgXAAIAAAAQgXAAgRAQg");

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-6.2,-6.2,12.5,12.5);


(lib.numdotlvl_red = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAjASIAAgcIgFAAIAAgEIACAAIACgBIACgCIAEAAIAAAjgAAGARQgDgCgBgDQgCgDAAgFIAAgIIACgHQABgDADgCQADgBADAAQADAAADABQADACACADQABADAAAEIAAAIQAAAIgDADQgDADgFAAQgFAAgCgBgAAQANIADgDIABgGIAAgHIgBgFQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAgBgBIgEgBIgEABQAAAAgBABQAAAAAAAAQgBABAAAAQAAABgBAAIAAAGIAAAHIAAAGQABAAAAABQAAAAABABQAAAAABABQAAAAAAAAQABAAAAABQABAAAAAAQABAAAAAAQABAAABAAIADgBgAgJASIAAgFIAFAAIAAAFgAgiARQgDgCgBgDQgBgDAAgFIAAgIIABgHQACgDACgCQADgBADAAQAEAAADABQADACABADQABADAAAEIAAAIQAAAIgDADQgDADgFAAQgEAAgDgBgAgXANIADgDIAAgGIAAgHIAAgFQgBgBAAAAQAAgBAAAAQgBgBAAAAQgBAAAAgBIgFgBIgDABQgBAAAAABQgBAAAAAAQAAABAAAAQgBABAAAAIgBAGIAAAHIABAGQAAAAABABQAAAAAAABQABAAAAABQAAAAABAAQAAAAABABQAAAAABAAQAAAAABAAQAAAAABAAIAEgBg");
	this.shape.setTransform(-0.1,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#035444").s().p("AgrAsQgSgSAAgaQAAgZASgSQASgSAZAAQAaAAASASQASASAAAZQAAAagSASQgSASgaAAQgZAAgSgSgAgogoQgQASAAAWQAAAXAQARQASARAWAAQAXAAARgRQARgRAAgXQAAgWgRgSQgRgQgXAAIAAAAQgXAAgRAQg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#109C81").s().p("AAAA5QgWAAgSgRQgQgRAAgXQAAgWAQgSQASgQAWAAQAXAAARAQQARASAAAWQAAAXgRARQgRARgXAAIAAAAgAAhgQIgCABIgDABIAAAEIAGAAIAAAcIAEAAIAAgjIgDAAIgCABgAgKASIAEAAIAAgGIgEAAgAgjgQQgDABgCAEIgBAHIAAAIQAAAFACADQABADADACQADABAEAAQAFAAADgDQADgEAAgHIAAgIQAAgEgBgDQgCgEgDgBQgDgCgDABQgDgBgDACgAgcAOQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIgBgGIAAgGIABgGQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIAEgBIAEABQABAAAAABQABAAAAABQAAAAABABQAAAAAAABIAAAFIAAAGIAAAGIgDAEIgCABIgBAAg");

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-6.2,-6.2,12.5,12.5);


(lib.numdotlvl_purple = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AACARQgCgCAAgDQgBgDAAgFIAAgIIABgHQAAgDACgCQADgBADAAQAEAAADABQACACACADQABADAAAEIAAAIQAAAIgDADQgDADgFAAQgEAAgDgBgAANANIACgDIABgGIAAgHIgBgFQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBIgFgBIgEABQAAAAAAABQgBAAAAAAQAAABgBAAQAAABAAAAIgBAGIAAAHIABAGQAAAAAAABQABAAAAABQAAAAABABQAAAAABAAQAAAAABABQAAAAAAAAQABAAABAAQAAAAABAAIAEgBgAgOASIAAgcIgFAAIAAgEIACAAIACgBIACgCIAEAAIAAAjg");
	this.shape.setTransform(-0.1,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E2318B").s().p("AgoApQgQgSAAgXQAAgWAQgSQASgQAWAAQAXAAASAQQAQASAAAWQAAAXgQASQgSAQgXAAQgWAAgSgQg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#B1045C").s().p("AgrAsQgSgSAAgaQAAgZASgSQASgSAZAAQAaAAASASQASASAAAZQAAAagSASQgSASgaAAQgZAAgSgSgAgogoQgQASAAAWQAAAXAQASQASAQAWAAQAXAAASgQQAQgSAAgXQAAgWgQgSQgSgQgXAAQgWAAgSAQg");

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-6.2,-6.2,12.5,12.5);


(lib.numdotlvl_pink = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAAASIAAgcIgDAAIAAgEIACAAIABgBIAAgCIAFAAIAAAjg");
	this.shape.setTransform(-0.1,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#009FE1").s().p("AAAA5QgWAAgSgRQgQgRAAgXQAAgWAQgSQASgQAWAAQAXAAARAQQARASAAAWQAAAXgRARQgRARgXAAIAAAAgAgBgQIgBABIgDABIAAAEIAFAAIAAAcIADAAIAAgjIgDAAIgBABg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006D9A").s().p("AgrAsQgSgSAAgaQAAgZASgSQASgSAZAAQAaAAASASQASASAAAZQAAAagSASQgSASgaAAQgZAAgSgSgAgogoQgQASAAAWQAAAXAQARQASARAWAAQAXAAARgRQARgRAAgXQAAgWgRgSQgRgQgXAAIAAAAQgXAAgRAQg");

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-6.2,-6.2,12.5,12.5);


(lib.numdotlvl_darkblue = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAVASIAAgcIgGAAIAAgEIADAAIABgBIACgCIAEAAIAAAjgAAEASIAAgFIAFAAIAAAFgAgTARQgDgCgBgDQgBgDAAgFIAAgIIABgHQABgDADgCQADgBADAAQAEAAADABQACACACADQABADAAAEIAAAIQAAAIgDADQgDADgFAAQgEAAgDgBgAgIANIACgDIABgGIAAgHIgBgFQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBIgFgBIgEABQAAAAAAABQgBAAAAAAQAAABgBAAQAAABAAAAIgBAGIAAAHIABAGQAAAAAAABQABAAAAABQAAAAABABQAAAAABAAQAAAAABABQAAAAAAAAQABAAABAAQAAAAABAAIAEgBg");
	this.shape.setTransform(-0.2,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D36240").s().p("AAAA5QgWAAgSgRQgQgRAAgXQAAgWAQgSQASgQAWAAQAXAAARAQQARASAAAWQAAAXgRARQgRARgXAAIAAAAgAASgQIgCABIgCABIAAAEIAFAAIAAAcIAFAAIAAgjIgFAAIgBABgAACASIAFAAIAAgGIgFAAgAgUgQQgEABgBAEIgBAHIAAAIQAAAFABADQABADAEACQACABAEAAQAFAAADgDQADgEABgHIAAgIQAAgEgCgDQgBgEgDgBQgDgCgEABQgDgBgCACgAgOAOQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQgBgBAAgBIgBgGIAAgGIABgGQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIADgBIAFABQAAAAABABQAAAAABABQAAAAAAABQAAAAABABIAAAFIAAAGIAAAGIgDAEIgDABIgBAAg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#982E0F").s().p("AgrAsQgSgSAAgaQAAgZASgSQASgSAZAAQAaAAASASQASASAAAZQAAAagSASQgSASgaAAQgZAAgSgSgAgogoQgQASAAAWQAAAXAQARQASARAWAAQAXAAARgRQARgRAAgXQAAgWgRgSQgRgQgXAAIAAAAQgXAAgRAQg");

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-6.2,-6.2,12.5,12.5);


(lib.pbPlus = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.ico_plus("single",0);
	this.instance.setTransform(13.4,10.8);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("AgSARIAAAAIgpAAIAAghIB3AAIAAAhIgqAAIAAAAg");
	this.shape.setTransform(12.5,10);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#993333").s().p("AgSASIAAgBIgpAAIAAgiIApAAIAAAAIAkAAIAAAAIAqAAIAAAiIgqAAIAAABg");
	this.shape_1.setTransform(12.5,10);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#EAEAEA").s().p("Ag7ARIAAgiIB3AAIAAAig");
	this.shape_2.setTransform(12.5,10);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).wait(1));

	// Layer 2
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("Ah8BjIAAjGID5AAIAADGg");
	this.shape_3.setTransform(12.5,10);

	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(4));

	// Layer 3
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("rgba(255,255,255,0)").s().p("Ah8BjIAAjGID5AAIAADGg");
	this.shape_4.setTransform(12.5,10);

	this.timeline.addTween(cjs.Tween.get(this.shape_4).wait(4));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,25,20);


(lib.mcInstruction = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AmYA3IAAg4IgXAAIAAgeIAXAAIAAg2IAfAAIAAA2IAXAAIAAAeIgXAAIAAA0QAPAHAIgHIAAAYQgFAIgNAAIgFAAQgHADgGAAQgSAAAAgfgAsUA3IAAg4IgXAAIAAgeIAXAAIAAg2IAfAAIAAA2IAWAAIAAAeIgWAAIAAA0QAPAHAHgHIAAAYQgEAIgNAAIgFAAQgHADgGAAQgSAAAAgfgANwArIAjAAQAIAMALABQAMgBAAgHQgIgJgNgDQgngIAAgaQAIghAnAAQAtABACAiIggAAQgBgHgPAAQgNABAAAEQgDAEAcAJQAkAHAEAXQgJAngqAAIgFAAQgqAAgGgpgAPtBUIAAggIAkAAIAAAggAM7BUIAAipIAgAAIAACpgAMGBUIAAgNQgNANgWAAQg6gIAAgyQAIg5AzAAQAVAAANANIAAgKIAeAAIAABwgALJAaQADAeAcAAQAdgFAAgZQgEgdgaAAQgeADAAAagAJ7BUIAAg/QgCgXgQAAQgVgHABAlIAAA4IggAAIAAg/QgBgXgSAAQgUgHABAlIAAA4IghAAIAAhzIAeAAIAAAJQAKgJAQAAQAVAAAMAPQANgPAXAAQAwAAAAAxIAABCgAG3BUIAAhzIAgAAIAABzgAErAaQAKg5AzAAQAsAAAQApIgjAAQgIgNgRAAQgdADAAAZQAEAfAaAAQAOABAKgPIAjAAQgSAqgpAAQg+gJAAgxgAChAaQAKg5AzAAQA8AJAAAxIgCAMIhVAAQAHARAVAAQAFACATgHIAhAAQgVAhgkAAQg+gJAAgxgAD9ARQgGgVgYAAQgWABgHAUIA7AAIAAAAgAByBUIAAgNQgNANgWAAQg6gJAAgxQAKg5AwAAQAUABANAJIAAhAIAfAAIAACpgAA1AZQAFAfAaAAQAegFAAgZQgEgdgbAAQgeADAAAZgAiqAaQALg5AzAAQA+AKAAAvQgLA6gzAAQg+gKAAgwgAiKAZQAGAfAYAAQAegFAAgZQgFgdgZAAQgeAEAAAYgAjxBUIgThDIgUBDIgTAAIgrhzIAjAAIASA8IARg8IAZAAIAQA8IATg8IAhAAIgpBzgAo9BUIAAhzIAdAAIAAAJQAHgJAPAAIACAAQAOACADADIAAAbQgIgCgJAAQgWAAABAWIAAA/gArNAaQAKg5AzAAQA8AJAAAxIgBAMIhWAAQAHARAVAAQAFACATgHIAhAAQgVAhgkAAQg+gJAAgxgApxARQgGgVgYAAQgWABgHAUIA7AAIAAAAgAteBUIAAg4QgBgegRAAQgMABgGAGQgEADAAAWIAAA2IggAAIAAhzIAeAAIAAAKQAMgKARAAQAZAAAMARQAJAKAAAbIAAA9gAwPBUIAAipIBUAAIAAAjIg0AAIAAAhIAyAAIAAAhIgyAAIAAAhIA0AAIAAAjgAG3g3IAAgeIAgAAIAAAeg");
	this.shape.setTransform(102.4,8.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FF9900").s().p("AgvhkIBfBkIhfBlg");
	this.shape_1.setTransform(99.5,9.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ah7C9IAAl6ID3AAIAAF6g");
	this.shape_2.setTransform(99.2,9.1);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AGEByIAAitIAcAAIAAALQAIgFAIgDQAJgDAKAAQAQAAANAIQANAHAIAOQAHANAAARQAAAQgIAOQgGANgOAHQgNAJgQgBQgKABgHgDQgJgCgGgFIAABBgAGwgaQgHAEgDAHQgFAHAAAIQAAAHAFAIQAEAHAGAEQAHAEAIAAQAJgBAGgDQAHgEAEgHQAEgHAAgIQAAgIgEgHQgEgHgHgEQgGgEgJAAQgIAAgHAEgAhYBoQgQgKgIgTIAjAAQAFAHAHACQAGADAJAAQAKAAAHgDQAGgEACgFQACgHAAgHIABgPQgIAHgIACQgHACgLAAQgRgBgMgIQgNgHgHgNQgIgOABgPQAAgQAHgNQAHgNANgIQAMgHARgBQALAAAIADQAJADAGAGIAAgKIAcAAIAABYQAAASgBAPQgCAPgDAMQgFAKgNAHQgMAGgVAAQgWAAgPgKgAhJgWQgIAIAAAOQAAANAIAHQAHAIAOAAQANAAAIgIQAIgIAAgMQgBgOgHgIQgIgIgNAAQgOAAgHAIgAELAqQgMgNAAgcIAAg8IAgAAIAAA5QAAAMACAGQACAHAFACQAEACAFAAQAGAAAFgDQAEgCADgDQACgEABgFIABgOIAAg3IAgAAIAAByIgeAAIAAgJQgHAFgGACQgIACgJAAIgBAAQgUAAgLgNgAdgA3IAAggIAjAAIAAAggAbwAwQgOgIgHgNQgJgNAAgPQAAgQAIgNQAIgNAOgIQAOgIARAAQARAAAOAIQANAIAHANQAIAOAAAQIAAAEIgBAHIhUAAQACAHAIAEQAGAFALAAIAHAAIAHgCIAJgDIAiAAQgFAOgJAGQgIAIgMACQgLADgLAAQgTAAgOgHgAcugKQgDgKgIgHQgHgFgMAAQgKAAgIAFQgHAGgEALIA7AAIAAAAgAafA3IAAg8QAAgKgCgGQgDgGgEgCQgEgCgGABQgGgBgEADQgFADgCAGQgDAIABALIAAA3IggAAIAAg8QAAgKgCgGQgDgGgEgCQgEgCgGABQgGgBgFADQgEADgDAGQgCAIAAALIAAA3IgeAAIAAhyIAdAAIAAAJQAEgFAHgCQAHgDAIABQALAAAIADQAIAEAGAIQAGgIAJgEQAJgDALAAQAXAAAMAMQANANAAAaIAAA/gAXcA3IAAgNQgHAHgIADQgIADgLAAQgRAAgNgHQgNgIgIgNQgHgNAAgPQAAgRAHgNQAIgNANgHQANgIASAAQAKAAAJADQAHADAHAGIAAgKIAeAAIAABwgAWogWQgIAIAAAOQAAALAIAIQAIAIANAAQAKAAAHgEQAGgEAEgHQAEgGgBgHQAAgIgDgHQgEgHgHgEQgHgEgJAAQgNAAgIAJgAVLA3IAAg3QAAgMgCgIQgCgGgFgDQgDgCgHABQgFgBgFACQgEADgDAFQgCACgBAGIgBAPIAAA1IggAAIAAhyIAeAAIAAAKQAHgFAGgDQAIgDAIABQAMAAAJAEQAJAEAHAJIAEAJQADAGAAAGQABAIAAAJIAAA7gASUAwQgOgIgHgNQgJgNAAgPQAAgQAIgNQAIgNAOgIQAOgIARAAQARAAAOAIQANAIAHANQAIAOAAAQIAAAEIgBAHIhVAAQAEAHAHAEQAGAFALAAIAHAAIAHgCIAJgDIAiAAQgFAOgJAGQgJAIgLACQgLADgLAAQgTAAgOgHgATSgKQgDgKgIgHQgHgFgMAAQgKAAgIAFQgIAGgDALIA7AAIAAAAgAQfA3IAAhyIAcAAIAAAJQAFgGAFgCQAFgCAIABIACAAIAGABIAGABIAFACIAAAeIgJgEIgIgBQgLABgGAGQgFAFAAAMIAAA9gAOwA3IAAgNQgIAHgHADQgJADgKAAQgRAAgNgHQgNgIgIgNQgHgNAAgPQAAgQAHgNQAIgNANgIQANgIARAAQAJAAAIACQAJADAFAFIAAhAIAgAAIAACogAOCgcQgGAFgFAHQgDAGAAAIQAAAHADAHQAFAHAHAEQAGAFAJAAQAIAAAHgFQAHgDADgIQAEgGABgHQgBgJgEgGQgDgIgHgDQgHgEgJAAQgIAAgHADgAMgA3IAAg3QAAgMgDgIQgCgGgEgDQgFgCgGABQgFgBgFACQgEADgDAFQgCACgBAGIgBAPIAAA1IgfAAIAAhyIAdAAIAAAKQAHgFAGgDQAIgDAIABQAMAAAJAEQAKAEAFAJIAGAJQABAGABAGQABAIgBAJIAAA7gAKhA3IAAgNQgIAHgHADQgJADgKAAQgSAAgNgHQgNgIgHgNQgIgNAAgPQAAgRAIgNQAHgNANgHQAOgIARAAQALAAAIADQAIADAHAGIAAgKIAdAAIAABwgAJsgWQgIAIAAAOQAAALAIAIQAJAIANAAQAJAAAHgEQAHgEAEgHQADgGAAgHQAAgIgEgHQgEgHgGgEQgIgEgIAAQgNAAgJAJgACSAvQgNgHgIgNQgJgOAAgOQAAgQAJgNQAHgNAOgIQAOgIARAAQARAAAPAIQAOAIAHANQAJANgBARQAAAOgIANQgIANgOAHQgNAIgSAAQgRAAgOgIgACjgbQgHAEgEAHQgEAHgBAHQABAIAEAGQAEAHAHAEQAGAEAIAAQAJAAAGgEQAHgEAEgHQAEgHAAgGQAAgIgEgHQgEgHgHgEQgGgEgJAAQgIAAgGAEgAAfA3IAAhyIAdAAIAAAJQAEgGAFgCQAGgCAHABIACAAIAHABIAGABIAEACIAAAeIgJgEIgIgBQgLABgGAGQgEAFAAAMIAAA9gAjcAwQgOgIgIgNQgJgNABgPQAAgQAIgNQAHgNAOgIQAOgIARAAQASAAANAIQANAIAIANQAHAOABAQIgBAEIAAAHIhVAAQADAHAHAEQAHAFALAAIAHAAIAGgCIAJgDIAiAAQgEAOgKAGQgIAIgMACQgLADgLAAQgSAAgOgHgAifgKQgDgKgHgHQgIgFgLAAQgLAAgHAFQgIAGgEALIA7AAIAAAAgAlSA3IAAhyIAdAAIAAAJQAFgGAEgCQAGgCAHABIACAAIAHABIAGABIAFACIAAAeIgJgEIgJgBQgLABgGAGQgEAFgBAMIAAA9gAn4AvQgOgHgIgNQgIgOgBgOQABgQAIgNQAIgNAOgIQAOgIARAAQARAAAOAIQAOAIAIANQAIANAAARQAAAOgIANQgJANgOAHQgNAIgRAAQgRAAgOgIgAnogbQgHAEgEAHQgDAHgBAHQABAIADAGQAEAHAHAEQAGAEAJAAQAIAAAHgEQAGgEAFgHQADgHAAgGQAAgIgDgHQgFgHgGgEQgHgEgIAAQgJAAgGAEgA2UAvQgNgHgJgNQgIgNAAgPQAAgQAIgNQAIgOAOgHQANgIARAAQAOAAALAEQAMAGAIAJQAJAKAGAOIgjAAQgFgIgFgEQgGgDgJAAQgNAAgHAJQgJAHAAAOQABAGADAHQAEAHAHAEQAGAEAJAAQAHAAAGgDQAGgDAFgIIAjAAQgJAVgPALQgOAKgVAAQgRAAgOgIgA4cAwQgOgIgIgNQgJgNAAgPQABgQAHgNQAJgNAOgIQANgIARAAQARAAAOAIQAOAIAHANQAIAOAAAQIAAAEIgBAHIhVAAQADAHAHAEQAHAFAKAAIAIAAIAHgCIAJgDIAhAAQgEAOgKAGQgIAIgLACQgLADgMAAQgSAAgOgHgA3fgKQgDgKgIgHQgHgFgMAAQgKAAgIAFQgHAGgEALIA7AAIAAAAgA5wA3IAAioIAgAAIAACogA7hAwQgOgIgJgNQgIgNAAgPQAAgQAIgNQAIgNAOgIQANgIASAAQARAAAOAIQANAIAIANQAHAOABAQIgBAEIgBAHIhVAAQADAHAHAEQAIAFAKAAIAHAAIAHgCIAJgDIAiAAQgFAOgJAGQgJAIgLACQgLADgMAAQgRAAgOgHgA6kgKQgEgKgHgHQgIgFgLAAQgLAAgHAFQgIAGgDALIA7AAIAAAAgA9lAxQgLgHgJgMQgHgMgCgQIAkAAQAAAKAHAEQAFAGAJAAQAKgBAFgFQAFgEAAgIQgBgDgDgBIgHgGIgIgFIgDgCIgCgBIgBAAIgEgCIgKgGQgKgGgIgFQgGgGgEgJQgEgHABgLQAAgNAGgLQAHgLALgGQAMgGAOAAQAOAAALAFQAMAHAHAKQAHAMABAQIgjAAQgBgJgFgEQgFgEgGAAQgHAAgEADQgDACgDADQgCADAAADIABAFIAEAFIAJAHIARAJQAVAKALAKQAMAMAAAKQAAAPgHAMQgIAMgMAHQgMAHgRAAQgPAAgNgGgApIA2IgKgEQgFgCgDgGQgEgGAAgKIAAg4IgXAAIAAgdIAXAAIAAg2IAgAAIAAA2IAVAAIAAAdIgWAAIAAA0QAAAEADABQADABAEAAIAHgDQADgBACgCIAAAYIgDACIgGAEQgEACgEAAIgFABIgJgBgA0DA2IgKgEQgFgCgEgGQgEgGAAgKIAAg4IgWAAIAAgdIAWAAIAAg2IAgAAIAAA2IAWAAIAAAdIgWAAIAAA0QAAAEACABQADABAEAAIAIgDQADgBABgCIAAAYIgDACIgGAEQgDACgFAAIgEABIgJgBgArkg0IAHgMIAEgIIACgFIABgFIgPAAIAAgeIAjAAIAAAbIgDALIgFAJIgEAHIgFAGgAsTg0IAIgMIADgIIACgFIABgFIgOAAIAAgeIAjAAIAAAbIgFALIgEAJIgEAHIgEAGgAxgg0IAAgbIAFgNIAEgJIAEgFIAEgGIASAAIgIALIgDAIIgCAGIgBAEIAOAAIAAAfgAyOg0IAAgbIAEgNIAFgJIAEgFIAFgGIARAAIgIALIgDAIIgCAGIgBAEIAOAAIAAAfg");
	this.shape_3.setTransform(191,10.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#CCCCCC").s().p("AgvhkIBfBkIhfBlg");
	this.shape_4.setTransform(99.5,9.1);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ah7C9IAAl6ID3AAIAAF6g");
	this.shape_5.setTransform(99.2,9.1);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("ABLBNQgNgIgJgNQgIgNAAgQQAAgRAIgLQAIgNAOgIQANgHARAAQAOAAALAEQAMAFAIAKQAJAJAGAMIgjAAQgFgHgFgEQgGgBgJAAQgNAAgHAGQgJAIAAAOQABAIADAHQAEAHAHAEQAGAEAJAAQAHAAAGgDQAGgEAFgHIAjAAQgJAVgPAKQgOALgVAAQgRAAgOgIgAg7BNQgOgHgIgNQgJgNAAgRQABgQAHgMQAJgNAOgHQANgIARAAQARAAAMAIQAOAHAHAOQAIALAAARIAAAGIgBAGIhTAAQADAIAHAEQAHAFAKAAIAIAAIAHgCIAJgDIAfAAQgEANgKAHQgIAHgJADQgLADgMAAQgSAAgOgIgAAAASQgBgLgIgGQgHgEgMAAQgKAAgIAEQgHAGgEALIA5AAIAAAAgAiPBVIAAioIAgAAIAACogAkABNQgOgHgJgNQgIgNAAgRQAAgQAIgMQAIgNAOgHQANgIASAAQARAAAOAIQANAHAIAOQAHALABARIgBAGIgBAGIhVAAQADAIAHAEQAIAFAKAAIAHAAIAHgCIAJgDIAiAAQgFANgJAHQgJAHgLADQgLADgMAAQgRAAgOgIgAjDASQgEgLgHgGQgIgEgLAAQgLAAgHAEQgIAGgDALIA7AAIAAAAgAmEBPQgLgHgJgMQgHgMgCgRIAkAAQAAALAHAEQAFAFAJAAQAKAAAFgFQAFgEAAgIQgBgDgDgDIgHgHIgIgEIgDgCIgCgBIgBgBIgEgCIgKgFQgKgGgIgEQgGgGgEgIQgEgHABgLQAAgNAGgLQAHgLALgGQAMgHAOAAQAOAAALAGQAMAGAHALQAHAMABAQIgjAAQgBgJgFgEQgFgEgGAAQgHAAgEACQgDADgDADQgCADAAADIABAFIAEAFIAJAGIARAJQAVALALAIQAMALAAAMQAAAQgHAMQgIAMgMAHQgMAHgRAAQgPAAgNgGgADcBUIgKgEQgFgCgEgGQgEgGAAgKIAAg4IgWAAIAAgdIAWAAIAAg2IAgAAIAAA2IAWAAIAAAdIgWAAIAAA0QAAAEACABQADABAEgBIAIgCQADgBABgCIAAAXIgDADIgGAEQgDACgFAAIgEAAIgJAAgAF/gWIAAgcIAFgMIAEgJIAEgGIAEgGIASAAIgIAMIgDAIIgCAGIgBAEIAOAAIAAAfgAFRgWIAAgcIAEgMIAFgJIAEgGIAFgGIARAAIgIAMIgDAIIgCAGIgBAEIAOAAIAAAfg");
	this.shape_6.setTransform(40.5,7.9);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AiHBIQgMgNAAgdIAAg8IAgAAIAAA3QAAAOACAHQACAGAFACQAEADAFgBQAGAAAFgCQAFgCACgEQACgDABgGIABgQIAAg1IAgAAIAAByIgeAAIAAgJQgGAFgHACQgHACgJAAIgCABQgUAAgLgNgAKnBUIAAgfIAjAAIAAAfgAHeBMQgNgHgJgNQgIgNAAgRQAAgQAIgLQAIgNAOgIQANgIASAAQANAAALAFQAMAFAJAJQAJAKAFAMIgjAAQgEgIgGgDQgGgCgIAAQgNAAgIAHQgIAIAAANQAAAJADAHQAEAHAHADQAHAEAIAAQAIAAAFgDQAGgDAFgIIAjAAQgIAVgPALQgPAKgUAAQgSAAgOgIgAGPBUIAAgNQgIAHgIADQgIADgLAAQgRAAgNgHQgNgIgHgNQgIgNAAgQQAAgRAIgMQAHgNANgHQAOgIARAAQAKAAAJADQAIADAHAHIAAgKIAdAAIAABvgAFaAFQgIAIAAAOQAAANAIAIQAIAIAOAAQAJAAAHgEQAHgEADgGQAEgHAAgIQAAgJgEgHQgEgHgHgEQgHgCgIAAQgOAAgIAHgADaBUIAAhyIAdAAIAAAJQAFgFAFgCQAFgCAHAAIACAAIAHABIAGACIAFACIAAAbIgJgCIgJAAQgLAAgFAEQgFAFAAAMIAAA/gAAdBRQgIgDgIgHIAAANIgbAAIAAioIAdAAIAABBQAHgGAIgCQAHgDAKAAQARAAANAIQANAHAIAOQAHALAAAQQAAARgHANQgHANgNAIQgNAHgQAAQgLAAgJgDgAAcAAQgHAEgEAGQgDAHAAAJQAAAOAIAIQAIAIAOABQANAAAIgJQAJgIAAgOQAAgJgEgGQgEgHgHgEQgHgCgJAAQgIAAgHACgAjxBQQgLgEgHgJQgHgKgCgOIAiAAQACAIAGACQAFADAGAAQAGAAADgCQAEgCAAgEQgBgDgDgCIgJgEIgJgCQgUgGgJgIQgKgHAAgNQAAgIAHgIQAGgIAKgEQALgFANAAQAMAAALAEQAKAEAGAJQAHAIABAKIghAAQgBgFgDAAQgEgDgHAAQgFAAgDADQgEAAAAADQAAABAAAAQAAABAAAAQABABAAAAQAAABABAAIAHAEIAPAFQAOAEAIAEQAIAEAEAFQAEAFABAIQACALgHAIQgHAJgMAFQgMAFgOAAQgOAAgLgEgAmuBMQgNgHgJgNQgIgOAAgQQAAgQAIgLQAIgNAOgIQAOgIARAAQARAAAOAIQAOAIAIANQAIALAAARQAAAQgIANQgIANgOAHQgOAIgRAAQgRAAgOgIgAmeAAQgGAEgEAHQgEAHgBAIQABAJAEAGQAEAHAGAEQAHAEAIAAQAIAAAHgEQAHgEAEgHQAEgGAAgJQAAgIgEgHQgEgHgHgEQgHgCgIAAQgIAAgHACgAJvBTIgKgDQgFgDgEgGQgDgFAAgLIAAg3IgXAAIAAgeIAXAAIAAg2IAfAAIAAA2IAWAAIAAAeIgWAAIAAA0QAAADADABQADABADAAIAIgCQADgCACgCIAAAYIgEADIgFAEQgEABgEAAIgFABIgJgBgACiBTIgKgDQgFgDgDgGQgEgFAAgLIAAg3IgXAAIAAgeIAXAAIAAg2IAgAAIAAA2IAWAAIAAAeIgXAAIAAA0QABADACABQADABAEAAIAHgCQAEgCABgCIAAAYIgDADIgGAEQgDABgFAAIgFABIgJgBgAn+BTIgKgDQgFgDgDgGQgEgFAAgLIAAg3IgXAAIAAgeIAXAAIAAg2IAgAAIAAA2IAWAAIAAAeIgXAAIAAA0QABADACABQADABAEAAIAHgCQAEgCABgCIAAAYIgDADIgGAEQgDABgFAAIgFABIgJgBgAqagXIAHgMIAEgIIACgFIABgFIgOAAIAAgeIAjAAIAAAbIgEAMIgFAJIgEAGIgEAGgArIgXIAHgMIADgIIACgFIABgFIgOAAIAAgeIAjAAIAAAbIgEAMIgEAJIgFAGIgEAGg");
	this.shape_7.setTransform(183.5,7.9);

	this.instance = new lib.ico_plus("single",0);
	this.instance.setTransform(96.7,10.5,1.187,1.186);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f().s("#FFFFFF").ss(1,1,1).p("ABzAZIjlAAIAAgxIDlAAg");
	this.shape_8.setTransform(95,9.6);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AhyAZIAAgxIDlAAIAAAxg");
	this.shape_9.setTransform(95,9.6);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("rgba(255,255,255,0)").s().p("Ah7B8IAAj3ID3AAIAAD3gAh4AZIDlAAIAAgwIjlAAg");
	this.shape_10.setTransform(95.6,9.5);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FF9900").s().p("AhHBYQgfgfAAgqQAAgjAXgdIgUgWQgDgDAAgGQAAgFADgFQADgFAGgBIBkgVQAGgBAFACQAFADACAFQACAFgCAFIgcBjQgCAFgEADQgFADgGAAQgFgBgEgEIgWgWQgKAOAAAQQAAAZASARQARASAXAAQAYAAARgSIABAAQARgRAAgZQAAgPgHgMQgLgQABgMQAFgTATACQALAEAMASQAOAXAAAbIAAACQAAAqgeAdQgeAfgrAAQgpAAgegfg");
	this.shape_11.setTransform(104.1,6.8);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AhZBrQgngnAAg1QAAghARgcIgGgHQgLgKAAgQQgBgOAJgMIAAgBQAJgMAPgDIABAAIBkgVIABAAQANgDAMAGIADABQAMAHAFAMIABABQAFANgEAOIAAABIgDAJQAIgCALABIAGABQARAFASAZIABACQASAdAAAjIAAACQgBA1glAlQgmAlg1AAQg0AAglglgAgWAnIAAAAQAKAKAMAAQANAAALgKIACgCQAIgJAAgNQAAgJgEgGIgDgEIgFAMQgEAOgLAIIgBAAQgKAJgOgCIgHgBIADADg");
	this.shape_12.setTransform(104.1,6.8);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("rgba(0,0,0,0.2)").s().p("AhiB0QgqgqAAg7QAAgfAOgcQgOgOgBgUQgBgTAMgPIABgBQALgPAQgFIAFgBIBkgVIACAAQARgDAPAHIABABIACABQAQAIAHARIABABQAFAOgCAOIADAAIAKACQAUAFAVAeIABACIABAAIAAABQATAgAAAmIAAACIAAAAQgBA6goApQgqApg7AAQg5AAgpgpg");
	this.shape_13.setTransform(104,6.8);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("rgba(0,0,0,0.2)").s().p("AicAQQgSgGAhgIQATgDAegEQgGgDALgCQAKgDAUgCIACAAIAmgEIAFAAIBxgDIACAAIAeABIACAAQALACgDACQgCACgKACIADAAIAAAAIAIAAQARABAEAFIAAAAQABAEgWAFIgCAAIAAAAQgjAJg/AFQg/AHg7gBQg7ABgRgHg");
	this.shape_14.setTransform(108.1,20.3);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#000000").s().p("AmqBJQgMgNAAgcIAAg8IAgAAIAAA3QAAANACAHQACAHAFACQAEACAFAAQAGAAAFgDQAEgCADgEQACgDABgFIABgQIAAg1IAgAAIAAByIgeAAIAAgKQgHAFgGADQgIACgJAAIgBAAQgUAAgLgNgEAi1ABWIAAggIAjAAIAAAggEAh7ABWIAAioIAgAAIAACogEAhCABWIAAgNQgHAHgJADQgIADgLAAQgQAAgNgIQgOgHgHgNQgIgNABgRQgBgRAIgLQAIgNANgIQANgHARAAQAKAAAJADQAIADAHAGIAAgKIAdAAIAABwgEAgNAAGQgIAJAAAOQAAANAIAIQAIAHAOABQAJAAAHgEQAHgEADgHQAEgGAAgJQAAgIgEgHQgEgHgHgEQgGgCgJAAQgOAAgIAGgAeyBWIAAg+QAAgLgCgFQgDgGgEgCQgEAAgFAAQgHAAgEABQgFACgCAHQgCAHAAANIAAA4IggAAIAAg+QAAgLgCgFQgCgGgFgCQgEAAgGAAQgGAAgFABQgEACgDAHQgBAHAAANIAAA4IggAAIAAhyIAeAAIAAAJQAFgFAGgCQAGgDAJAAQALAAAIAEQAIAEAGAIQAGgIAJgEQAJgEALAAQAXABAMAMQAMANAAAYIAABBgAbsBWIAAhyIAfAAIAABygAZ9BOQgOgIgIgNQgIgNAAgQQAAgRAIgLQAIgNAOgIQANgHARAAQANAAAMAEQALAFAJAKQAJAJAGAMIgjAAQgEgHgGgEQgGgBgJAAQgNAAgHAGQgJAIABAOQgBAIAEAHQAEAHAGAEQAIAEAIAAQAIAAAFgDQAGgEAFgHIAjAAQgJAVgPAKQgOALgVAAQgRAAgOgIgAX1BOQgOgHgIgNQgJgNAAgRQAAgQAIgMQAJgNANgHQAOgIASAAQAQAAAOAIQAOAHAHANQAIAMAAARIgBAGIgBAGIhUAAQADAIAHAEQAHAFAKAAIAIAAIAHgCIAJgDIAhAAQgFANgIAHQgJAHgLADQgMADgLAAQgSAAgOgIgAYyATQgDgLgIgGQgHgEgMAAQgKAAgIAEQgHAGgDALIA6AAIAAAAgAWkBWIAAgNQgIAHgHADQgJADgKAAQgRAAgNgIQgNgHgIgNQgHgNAAgRQAAgQAHgMQAIgNANgHQANgIARAAQAJAAAIACQAJADAFAFIAAhAIAgAAIAACogAV2ABQgHAEgEAHQgDAHAAAIQAAAJADAHQAFAHAGAEQAHAEAJAAQAIAAAHgEQAHgEAEgHQADgGAAgJQAAgJgDgHQgEgHgHgDQgHgCgJgBQgIABgHABgAS4BWIAAhyIAdAAIAAAIQAEgFAGgCQAFgCAHABIACAAIAHAAIAGACIAEACIAAAbIgJgDIgIAAQgLAAgGAFQgEAGAAAMIAAA/gARJBOQgOgHgJgNQgIgNAAgRQAAgQAIgMQAIgNAOgHQANgIASAAQARAAAOAIQANAHAHANQAIAMABARIgBAGIgBAGIhVAAQAEAIAGAEQAIAFAKAAIAHAAIAHgCIAJgDIAiAAQgFANgJAHQgJAHgLADQgLADgMAAQgRAAgOgIgASGATQgEgLgHgGQgIgEgLAAQgLAAgHAEQgIAGgDALIA7AAIAAAAgAP4BWIAAg4QAAgMgCgGQgCgGgFgDQgEgDgHAAQgGAAgFADQgFADgCAGQgDAGAAAMIAAA4IgfAAIAAioIAfAAIAABAQAFgEAHgCQAHgCAHAAQAVAAANAMQALANAAAZIAAA+gALjBOQgNgIgJgNQgIgNAAgQQAAgQAIgMQAIgNAOgHQANgIASAAQARAAAOAIQAOAHAIANQAIAMAAARQAAAPgJANQgHANgOAIQgOAIgRAAQgRAAgOgIgALzACQgGAEgEAGQgFAHAAAIQAAAJAFAHQAEAHAGAEQAGAEAJAAQAIAAAHgEQAGgEAEgHQAFgHAAgIQAAgJgFgGQgEgHgGgEQgHgCgIAAQgJAAgGACgAKTBWIAAg4QAAgOgDgHQgCgHgEgCQgEAAgGAAQgGAAgEAAQgFADgDAEQgCADAAAGIgBAQIAAA2IggAAIAAhyIAeAAIAAAKQAGgGAHgCQAHgDAJAAQALABAJAEQAKAEAGAIIAFAKQACADABAHQAAAHAAAKIAAA9gAIUBWIAAgNQgHAHgIADQgJADgKAAQgRAAgNgIQgOgHgGgNQgIgNAAgRQAAgRAIgLQAHgNANgIQAOgHAQAAQALAAAJADQAIADAGAGIAAgKIAdAAIAABwgAHfAGQgHAJgBAOQABANAHAIQAJAHAOABQAJAAAHgEQAGgEAEgHQADgGAAgJQAAgIgDgHQgFgHgGgEQgHgCgIAAQgOAAgJAGgAC7BOQgNgIgJgNQgIgNAAgQQAAgRAIgLQAIgNAOgIQANgHARAAQAOAAALAEQAMAFAIAKQAJAJAGAMIgjAAQgFgHgFgEQgGgBgJAAQgNAAgHAGQgJAIAAAOQABAIADAHQAEAHAHAEQAGAEAJAAQAHAAAGgDQAGgEAFgHIAjAAQgJAVgPAKQgOALgVAAQgRAAgOgIgABsBWIAAgNQgIAHgIADQgJADgKAAQgRAAgNgIQgOgHgGgNQgIgNAAgRQAAgRAIgLQAHgNANgIQANgHARAAQALAAAIADQAIADAIAGIAAgKIAcAAIAABwgAA2AGQgHAJgBAOQABANAHAIQAJAHAOABQAJAAAGgEQAIgEADgHQADgGABgJQAAgIgFgHQgEgHgGgEQgHgCgIAAQgOAAgJAGgAhHBWIAAhyIAdAAIAAAIQAFgFAEgCQAGgCAHABIACAAIAHAAIAGACIAFACIAAAbIgJgDIgJAAQgLAAgGAFQgEAGgBAMIAAA/gAkEBTQgIgDgJgHIAAANIgcAAIAAioIAfAAIAABAQAGgFAIgDQAIgCAKAAQARAAAMAHQAOAIAIANQAHALAAARQAAAQgHANQgIANgMAIQgNAIgRAAQgLAAgIgDgAkFABQgHAEgEAHQgDAHgBAJQABAOAHAIQAJAIAOAAQANAAAIgIQAJgIAAgOQAAgJgFgHQgEgHgGgEQgHgBgJgBQgJABgGABgAoUBSQgLgFgHgJQgHgJgCgOIAhAAQADAHAFADQAGADAGAAQAGAAADgCQADgDAAgDQAAgEgDgCIgJgDIgJgDQgUgFgKgIQgJgIAAgMQAAgIAGgIQAHgIAKgFQALgEANAAQAMAAAKAEQALAEAGAIQAHAIABAKIghAAQgBgFgDgBQgEgBgIAAQgEAAgEABQgDABAAAEQAAAAAAABQAAAAAAABQAAAAABABQAAAAAAABIAIADIAPAFQAOAEAHAEQAJAFAEAFQAEAFABAHQACALgIAJQgGAIgMAGQgMAFgOAAQgOAAgLgEgArRBOQgOgIgIgNQgIgNgBgQQABgQAIgMQAIgNAOgHQAOgIAQAAQASAAAOAIQAOAHAIANQAIAMAAARQAAAPgJANQgIANgNAIQgOAIgRAAQgRAAgOgIgArBACQgGAEgFAGQgEAHAAAIQAAAJAEAHQAFAHAGAEQAGAEAJAAQAIAAAHgEQAHgEADgHQAEgHAAgIQAAgJgEgGQgDgHgHgEQgHgCgIAAQgJAAgGACgAN2BVIgKgEQgFgCgEgGQgDgGAAgKIAAg5IgXAAIAAgcIAXAAIAAg2IAgAAIAAA2IAVAAIAAAcIgWAAIAAA1QAAAEADABQADABAEgBIAHgCQADgBACgCIAAAXIgDADIgGAEQgEACgEAAIgFAAIgJAAgAFMBVIgKgEQgFgCgEgGQgEgGAAgKIAAg5IgWAAIAAgcIAWAAIAAg2IAgAAIAAA2IAWAAIAAAcIgWAAIAAA1QAAAEACABQADABAEgBIAIgCQADgBABgCIAAAXIgDADIgGAEQgDACgFAAIgEAAIgJAAgAh/BVIgKgEQgFgCgDgGQgEgGAAgKIAAg5IgXAAIAAgcIAXAAIAAg2IAgAAIAAA2IAVAAIAAAcIgWAAIAAA1QAAAEADABQADABAEgBIAHgCQADgBACgCIAAAXIgDADIgGAEQgEACgEAAIgFAAIgJAAgAshBVIgKgEQgFgCgDgGQgEgGAAgKIAAg5IgXAAIAAgcIAXAAIAAg2IAgAAIAAA2IAVAAIAAAcIgWAAIAAA1QAAAEADABQADABAEgBIAHgCQADgBACgCIAAAXIgDADIgGAEQgDACgFAAIgFAAIgJAAgA7pBLQgNgHgIgNQgJgNAAgRQAAgQAJgLQAHgNAOgIQAOgIARAAQANAAALAFQAMAFAJAJQAJAKAFAMIgjAAQgEgIgGgCQgGgDgIAAQgNAAgIAHQgIAIAAANQAAAJAEAHQADAHAHADQAHAEAJAAQAHAAAFgDQAHgDAEgIIAjAAQgIAVgPALQgPAKgUAAQgSAAgOgIgA9xBMQgOgIgHgNQgJgNAAgQQAAgRAIgLQAIgNAOgIQAOgIARAAQARAAANAIQAOAIAHANQAIAMAAARIAAAFIgBAHIhUAAQACAHAIAFQAGAEALAAIAIAAIAGgBIAJgDIAiAAQgFANgJAHQgJAHgLADQgLACgLAAQgTAAgOgHgA80AQQgCgKgIgGQgHgEgMAAQgLAAgHAEQgHAFgEALIA6AAIAAAAgA/EBTIAAioIAfAAIAACogEgg2ABMQgOgIgIgNQgIgNAAgQQgBgRAJgLQAHgNAOgIQAOgIASAAQARAAANAIQANAIAIANQAHAMABARIgBAFIgBAHIhUAAQADAHAHAFQAHAEALAAIAHAAIAGgBIAJgDIAiAAQgFANgIAHQgJAHgMADQgKACgMAAQgSAAgOgHgA/5AQQgDgKgHgGQgIgEgLAAQgLAAgHAEQgIAFgDALIA6AAIAAAAgEgi5ABNQgMgGgIgMQgHgMgDgRIAkAAQABAKAGAFQAGAFAJAAQAJgBAFgEQAFgFAAgHQAAgEgDgDIgHgGIgIgFIgDgBIgDgCIgBAAIgDgCIgKgGQgLgEgHgFQgHgGgDgIQgEgIAAgKQAAgOAHgLQAHgKALgHQAMgGAOAAQAOAAALAGQALAGAIALQAGALACAQIgjAAQgCgJgEgEQgFgEgGAAQgHAAgEADQgEACgCADQgCADAAADIABAFIADAFIAJAHIARAJQAVAKAMAJQALALAAAMQAAAPgHAMQgHAMgNAHQgMAHgQAAQgQAAgMgGgA5YBSIgKgDQgFgDgEgGQgDgFAAgLIAAg3IgXAAIAAgeIAXAAIAAg2IAfAAIAAA2IAXAAIAAAeIgXAAIAAA0QABADACABQADABADAAIAIgCQADgCACgCIAAAYIgEADIgFAEQgDABgFAAIgFABIgJgBgAu6gYIAHgMIAEgIIABgFIABgFIgNAAIAAgeIAjAAIAAAbIgFAMIgEAJIgFAGIgDAGgAvogYIAGgMIAEgIIACgFIABgFIgOAAIAAgeIAjAAIAAAbIgEAMIgEAJIgFAGIgEAGgA20gYIAAgbIAEgMIAEgJIAEgGIAFgGIARAAIgHAMIgEAIIgCAFIAAAFIANAAIAAAegA3jgYIAAgbIAFgMIAEgJIAFgGIAEgGIARAAIgHAMIgEAIIgBAFIgBAFIANAAIAAAegAbsg0IAAgeIAgAAIAAAeg");
	this.shape_15.setTransform(225,8);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3},{t:this.shape_2},{t:this.shape_1}]},1).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.instance},{t:this.shape_7},{t:this.shape_6}]},1).to({state:[{t:this.shape_15},{t:this.shape_14},{t:this.shape_13},{t:this.shape_12},{t:this.shape_11}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-1.7,-0.3,208.2,17.4);


(lib.cbModel_Tenths1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// highlight
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AAiAqIhHhPIAAgCIAAgCIACgBIACABIBGBPIABACIgBACIgCABIgBgBg");
	this.shape.setTransform(4.9,5.2);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1).to({_off:false},0).wait(1));

	// cube
	this.instance = new lib.numdotlvl_yellow("single",0);
	this.instance.setTransform(5,5,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// hit
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0)").s().p("AgxAxIAAhiIBiAAIAABig");
	this.shape_1.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10,10);


(lib.cbModel_Tenths = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// highlight
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AAiAqIhHhPIAAgCIAAgCIACgBIACABIBGBPIABACIgBACIgCABIgBgBg");
	this.shape.setTransform(4.9,5.2);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1).to({_off:false},0).wait(1));

	// cube
	this.instance = new lib.numdotlvl_darkblue("single",0);
	this.instance.setTransform(5,5,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// hit
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0)").s().p("AgxAxIAAhiIBiAAIAABig");
	this.shape_1.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10,10);


(lib.cbModel_Tens1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// highlight
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AAiAqIhHhPIAAgCIAAgCIACgBIACABIBGBPIABACIgBACIgCABIgBgBg");
	this.shape.setTransform(4.9,5.2);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1).to({_off:false},0).wait(1));

	// cube
	this.instance = new lib.numdotlvl_purple("single",0);
	this.instance.setTransform(5,5,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// hit
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0)").s().p("AgxAxIAAhiIBiAAIAABig");
	this.shape_1.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10,10);


(lib.cbModel_Tens = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// highlight
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AAiAqIhHhPIAAgCIAAgCIACgBIACABIBGBPIABACIgBACIgCABIgBgBg");
	this.shape.setTransform(4.9,5.2);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1).to({_off:false},0).wait(1));

	// cube
	this.instance = new lib.numdotlvl_purple("single",0);
	this.instance.setTransform(5,5,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// hit
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0)").s().p("AgxAxIAAhiIBiAAIAABig");
	this.shape_1.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10,10);


(lib.cbModel_Ones1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// highlight
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AAiAqIhHhPIAAgCIAAgCIACgBIACABIBGBPIABACIgBACIgCABIgBgBg");
	this.shape.setTransform(4.9,5.2);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1).to({_off:false},0).wait(1));

	// cube
	this.instance = new lib.numdotlvl_pink("single",0);
	this.instance.setTransform(5,5,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// hit
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0)").s().p("AgxAxIAAhiIBiAAIAABig");
	this.shape_1.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10,10);


(lib.cbModel_Ones = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// highlight
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AAiAqIhHhPIAAgCIAAgCIACgBIACABIBGBPIABACIgBACIgCABIgBgBg");
	this.shape.setTransform(4.9,5.2);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1).to({_off:false},0).wait(1));

	// cube
	this.instance = new lib.numdotlvl_pink("single",0);
	this.instance.setTransform(5,5,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// hit
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0)").s().p("AgxAxIAAhiIBiAAIAABig");
	this.shape_1.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10,10);


(lib.cbModel_Hundredths1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// highlight
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AAiAqIhHhPIAAgCIAAgCIACgBIACABIBGBPIABACIgBACIgCABIgBgBg");
	this.shape.setTransform(4.9,5.2);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1).to({_off:false},0).wait(1));

	// cube
	this.instance = new lib.numdotlvl_red("single",0);
	this.instance.setTransform(5,5,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// hit
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0)").s().p("AgxAxIAAhiIBiAAIAABig");
	this.shape_1.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10,10);


(lib.cbModel_Hundredths = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// highlight
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF0000").s().p("AAiAqIhHhPIAAgCIAAgCIACgBIACABIBGBPIABACIgBACIgCABIgBgBg");
	this.shape.setTransform(4.9,5.2);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1).to({_off:false},0).wait(1));

	// cube
	this.instance = new lib.numdotlvl_red("single",0);
	this.instance.setTransform(5,5,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// hit
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(255,255,255,0)").s().p("AgxAxIAAhiIBiAAIAABig");
	this.shape_1.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10,10);


(lib.mc_cbModel_Tenths1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.cbModel_Tenths = new lib.cbModel_Tenths1();
	this.cbModel_Tenths.setTransform(0,0,4,4);

	this.timeline.addTween(cjs.Tween.get(this.cbModel_Tenths).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,40,40);


(lib.mc_cbModel_Tenths = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.cbModel_Tenths = new lib.cbModel_Tenths();
	this.cbModel_Tenths.setTransform(14,8.3,1,1,0,0,0,14,8.3);

	this.timeline.addTween(cjs.Tween.get(this.cbModel_Tenths).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10,10);


(lib.mc_cbModel_Tens1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.cbModel_Tens = new lib.cbModel_Tens1();
	this.cbModel_Tens.setTransform(0,0,4,4);

	this.timeline.addTween(cjs.Tween.get(this.cbModel_Tens).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,40,40);


(lib.mc_cbModel_Tens = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.cbModel_Tens = new lib.cbModel_Tens();
	this.cbModel_Tens.setTransform(14,8.3,1,1,0,0,0,14,8.3);

	this.timeline.addTween(cjs.Tween.get(this.cbModel_Tens).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10,10);


(lib.mc_cbModel_Ones1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.cbModel_Ones = new lib.cbModel_Ones1();
	this.cbModel_Ones.setTransform(20,20,4,4,0,0,0,5,5);

	this.timeline.addTween(cjs.Tween.get(this.cbModel_Ones).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,40,40);


(lib.mc_cbModel_Ones = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.cbModel_Ones = new lib.cbModel_Ones();
	this.cbModel_Ones.setTransform(14.4,16,4,4,0,0,0,3.6,4);

	this.timeline.addTween(cjs.Tween.get(this.cbModel_Ones).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,40,40);


(lib.mc_cbModel_Hundredths1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.cbModel_Hundredths = new lib.cbModel_Hundredths1();
	this.cbModel_Hundredths.setTransform(20,20,4,4,0,0,0,5,5);

	this.timeline.addTween(cjs.Tween.get(this.cbModel_Hundredths).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,40,40);


(lib.mc_cbModel_Hundredths = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.cbModel_Hundredths = new lib.cbModel_Hundredths();
	this.cbModel_Hundredths.setTransform(20,20,4,4,0,0,0,5,5);

	this.timeline.addTween(cjs.Tween.get(this.cbModel_Hundredths).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,40,40);


(lib.mcClone = function() {
	this.initialize();

	// Layer 1
	this.mc_cbModel_Hundredths1 = new lib.mc_cbModel_Hundredths1();
	this.mc_cbModel_Hundredths1.setTransform(126.9,0.1,1,0.999);

	this.mc_cbModel_Hundredths = new lib.mc_cbModel_Hundredths();
	this.mc_cbModel_Hundredths.setTransform(126.9,48.1,1,0.999);

	this.mc_cbModel_Tens1 = new lib.mc_cbModel_Tens1();
	this.mc_cbModel_Tens1.setTransform(0,0.1,1,0.999);

	this.mc_cbModel_Tens = new lib.mc_cbModel_Tens();
	this.mc_cbModel_Tens.setTransform(0,48.1,4,3.997);

	this.mc_cbModel_Ones = new lib.mc_cbModel_Ones();
	this.mc_cbModel_Ones.setTransform(84.6,48);

	this.mc_cbModel_Ones1 = new lib.mc_cbModel_Ones1();
	this.mc_cbModel_Ones1.setTransform(42.3,48);

	this.mc_cbModel_Tenths = new lib.mc_cbModel_Tenths();
	this.mc_cbModel_Tenths.setTransform(42.3,0,4,4);

	this.mc_cbModel_Tenths1 = new lib.mc_cbModel_Tenths1();
	this.mc_cbModel_Tenths1.setTransform(84.6,0);

	this.addChild(this.mc_cbModel_Tenths1,this.mc_cbModel_Tenths,this.mc_cbModel_Ones1,this.mc_cbModel_Ones,this.mc_cbModel_Tens,this.mc_cbModel_Tens1,this.mc_cbModel_Hundredths,this.mc_cbModel_Hundredths1);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,166.9,88);


// stage content:



(lib.placevaluechart_sub10_10_canvas = function() {
	this.initialize();

	// Instruction
	this.mcInstruction = new lib.mcInstruction();
	this.mcInstruction.setTransform(447.7,60.6,1,1,0,0,0,414.4,11.6);

	// Tool
	this.mcClone = new lib.mcClone();
	this.mcClone.setTransform(838.1,108.3);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgJAMIAAgXIATAAIAAAXg");
	this.shape.setTransform(870.3,311.9);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.004)").s().p("AhiC9IAAl5IDFAAIAAF5gAgJBGIATAAIAAgaIgTAAg");
	this.shape_1.setTransform(870.3,306.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#000000").s().p("AgJAMIAAgXIATAAIAAAXg");
	this.shape_2.setTransform(870.3,363.4);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(0,0,0,0.004)").s().p("AhiC9IAAl6IDFAAIAAF6gAgJBFIATAAIAAgZIgTAAg");
	this.shape_3.setTransform(870.3,357.6);

	this.mcDecimal = new lib.mcDecimal();
	this.mcDecimal.setTransform(875.3,425.2,1,1,0,0,0,15,18);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(1,2,0,3).p("ATsFFMgnXAAAATslEMgnXAAA");
	this.shape_4.setTransform(870.5,416.6);

	this.mcChangeValue_Tens = new lib.mcValueChange_Thousands();
	this.mcChangeValue_Tens.setTransform(808,267.5,1,1,0,0,0,47.3,14.8);

	this.tfNum_Tens2 = new cjs.Text("", "22px 'AMCE Basic'");
	this.tfNum_Tens2.name = "tfNum_Tens2";
	this.tfNum_Tens2.textAlign = "center";
	this.tfNum_Tens2.lineHeight = 24;
	this.tfNum_Tens2.lineWidth = 30;
	this.tfNum_Tens2.setTransform(773.2,401.4);

	this.tfSelect_Tens = new cjs.Text("00", "22px 'AMCE Basic'");
	this.tfSelect_Tens.name = "tfSelect_Tens";
	this.tfSelect_Tens.textAlign = "center";
	this.tfSelect_Tens.lineHeight = 24;
	this.tfSelect_Tens.lineWidth = 31;
	this.tfSelect_Tens.setTransform(773.6,333.5);

	this.tfNum_Tens = new cjs.Text("00", "22px 'AMCE Basic'");
	this.tfNum_Tens.name = "tfNum_Tens";
	this.tfNum_Tens.textAlign = "center";
	this.tfNum_Tens.lineHeight = 24;
	this.tfNum_Tens.lineWidth = 32;
	this.tfNum_Tens.setTransform(774,281.7);

	this.pbBreak_Tens = new lib.mcArrow();
	this.pbBreak_Tens.setTransform(202.2,299.6,1.187,1.187);

	this.pbMin_Tens1 = new lib.pbPlus();
	this.pbMin_Tens1.setTransform(139.2,524.7,1.187,1.186,0,0,0,16,16);

	this.mcPanel_Tens = new lib.mcLeftPanel();
	this.mcPanel_Tens.setTransform(65,130.6,0.586,1.223);
	this.mcPanel_Tens.alpha = 0;

	this.mcChangeValue_Tenths = new lib.mcValueChange_Tens();
	this.mcChangeValue_Tenths.setTransform(936.8,267.5,1,1,0,0,0,47.3,14.8);

	this.pbMin_Ones1 = new lib.pbPlus();
	this.pbMin_Ones1.setTransform(293.4,524.7,1.187,1.186,0,0,0,16,16);

	this.pbBreak_Ones = new lib.mcArrow();
	this.pbBreak_Ones.setTransform(359.6,299.6,1.187,1.187);

	this.mcPanel_Ones = new lib.mcLeftPanel();
	this.mcPanel_Ones.setTransform(219.2,130.6,0.586,1.223);
	this.mcPanel_Ones.alpha = 0;

	this.mcChangeValue_Ones = new lib.mcValueChange_Hundreds();
	this.mcChangeValue_Ones.setTransform(867,267.5,1,1,0,0,0,47.3,14.8);

	this.tfNum_Ones2 = new cjs.Text("", "22px 'AMCE Basic'");
	this.tfNum_Ones2.name = "tfNum_Ones2";
	this.tfNum_Ones2.textAlign = "center";
	this.tfNum_Ones2.lineHeight = 24;
	this.tfNum_Ones2.lineWidth = 30;
	this.tfNum_Ones2.setTransform(832.2,401.4);

	this.tfSelect_Ones = new cjs.Text("00", "22px 'AMCE Basic'");
	this.tfSelect_Ones.name = "tfSelect_Ones";
	this.tfSelect_Ones.textAlign = "center";
	this.tfSelect_Ones.lineHeight = 24;
	this.tfSelect_Ones.lineWidth = 31;
	this.tfSelect_Ones.setTransform(832.6,333.5);

	this.tfNum_Ones = new cjs.Text("00", "22px 'AMCE Basic'");
	this.tfNum_Ones.name = "tfNum_Ones";
	this.tfNum_Ones.textAlign = "center";
	this.tfNum_Ones.lineHeight = 24;
	this.tfNum_Ones.lineWidth = 32;
	this.tfNum_Ones.setTransform(833,281.7);

	this.mcChangeValue_Hundredths = new lib.mcValueChange_Ones();
	this.mcChangeValue_Hundredths.setTransform(994.5,266.5,1,1,0,0,0,47.3,14.8);

	this.mcWarning = new lib.mcWarning();
	this.mcWarning.setTransform(511.8,582.5,1,1,0,0,0,348.2,14.8);

	this.pbMin_Hundredths1 = new lib.pbPlus();
	this.pbMin_Hundredths1.setTransform(613.1,524.7,1.187,1.186,0,0,0,16,16);

	this.pbMin_Tenths1 = new lib.pbPlus();
	this.pbMin_Tenths1.setTransform(458.5,524.7,1.187,1.186,0,0,0,16,16);

	this.pbBreak_Tenths = new lib.mcArrow();
	this.pbBreak_Tenths.setTransform(520.5,299.6,1.187,1.187);

	this.tfNum_Hundredths2 = new cjs.Text("", "22px 'AMCE Basic'");
	this.tfNum_Hundredths2.name = "tfNum_Hundredths2";
	this.tfNum_Hundredths2.textAlign = "center";
	this.tfNum_Hundredths2.lineHeight = 24;
	this.tfNum_Hundredths2.lineWidth = 31;
	this.tfNum_Hundredths2.setTransform(962.5,401.4);

	this.tfNum_Tenths2 = new cjs.Text("", "22px 'AMCE Basic'");
	this.tfNum_Tenths2.name = "tfNum_Tenths2";
	this.tfNum_Tenths2.textAlign = "center";
	this.tfNum_Tenths2.lineHeight = 24;
	this.tfNum_Tenths2.lineWidth = 30;
	this.tfNum_Tenths2.setTransform(902.2,401.4);

	this.tfSelect_Hundredths = new cjs.Text("00", "22px 'AMCE Basic'");
	this.tfSelect_Hundredths.name = "tfSelect_Hundredths";
	this.tfSelect_Hundredths.textAlign = "center";
	this.tfSelect_Hundredths.lineHeight = 24;
	this.tfSelect_Hundredths.lineWidth = 31;
	this.tfSelect_Hundredths.setTransform(962.7,333.5);

	this.tfNum_Hundredths = new cjs.Text("00", "22px 'AMCE Basic'");
	this.tfNum_Hundredths.name = "tfNum_Hundredths";
	this.tfNum_Hundredths.textAlign = "center";
	this.tfNum_Hundredths.lineHeight = 24;
	this.tfNum_Hundredths.lineWidth = 32;
	this.tfNum_Hundredths.setTransform(962.9,281.7);

	this.tfSelect_Tenths = new cjs.Text("00", "22px 'AMCE Basic'");
	this.tfSelect_Tenths.name = "tfSelect_Tenths";
	this.tfSelect_Tenths.textAlign = "center";
	this.tfSelect_Tenths.lineHeight = 24;
	this.tfSelect_Tenths.lineWidth = 31;
	this.tfSelect_Tenths.setTransform(902.6,333.5);

	this.tfNum_Tenths = new cjs.Text("00", "22px 'AMCE Basic'");
	this.tfNum_Tenths.name = "tfNum_Tenths";
	this.tfNum_Tenths.textAlign = "center";
	this.tfNum_Tenths.lineHeight = 24;
	this.tfNum_Tenths.lineWidth = 32;
	this.tfNum_Tenths.setTransform(903,281.7);

	this.mcPanel_Hundredths = new lib.mcLeftPanel();
	this.mcPanel_Hundredths.setTransform(539,130.6,0.586,1.223);
	this.mcPanel_Hundredths.alpha = 0;

	this.mcPanel_Tenths = new lib.mcLeftPanel();
	this.mcPanel_Tenths.setTransform(384.3,130.6,0.586,1.223);
	this.mcPanel_Tenths.alpha = 0;

	// addon
	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AA1BmQgGgGAAgLIAAhCIhdAAIAABCQAAALgGAGQgGAGgKAAQgKAAgGgGQgHgGAAgLIAAipQAAgLAHgGQAGgGAKAAQAKAAAGAGQAGAGAAALIAABAIBdAAIAAhAQAAgLAGgGQAGgGAKAAQAKAAAGAGQAGAGABALIAACpQgBALgGAGQgGAGgKAAQgKAAgGgGg");
	this.shape_5.setTransform(964.4,210);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AgOBlQgHgGAAgLIAAiVIghAAQgKAAgFgGQgFgHAAgIQAAgIAGgGQAFgGAJAAIBtAAQAJAAAFAGQAGAGAAAIQAAAIgFAHQgFAGgKAAIghAAIAACVQAAALgHAGQgGAGgJAAQgJAAgFgGg");
	this.shape_6.setTransform(905,210.1);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#D36240").s().p("AkpDIIAAmPIJTAAIAAGPg");
	this.shape_7.setTransform(905,210);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#109C81").s().p("AkpDIIAAmPIJTAAIAAGPg");
	this.shape_8.setTransform(964.4,210);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgPBlQgGgGAAgLIAAiVIghAAQgKAAgGgGQgEgHAAgIQAAgIAFgGQAGgGAJAAIBsAAQALAAAFAGQAFAGAAAIQAAAIgFAHQgEAGgMAAIggAAIAACVQAAALgGAGQgHAGgJAAQgJAAgGgGg");
	this.shape_9.setTransform(774.6,210.1);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag0BfQgXgOgNgZQgNgZgBgfQABgeANgZQAMgZAYgOQAXgPAdAAQAeAAAXAPQAXAPANAZQANAZABAdQAAAfgNAZQgNAZgXAOQgXAPgfAAQgdAAgXgPgAgeg6QgMAKgHAPQgGAQAAARQAAASAGAQQAGAPANAKQAMAJASAAQATAAAMgJQANgKAGgPQAGgQAAgSQAAgRgGgQQgHgPgMgKQgNgJgSgBQgRABgNAJg");
	this.shape_10.setTransform(832,210.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#E2318B").s().p("AkpDIIAAmPIJTAAIAAGPg");
	this.shape_11.setTransform(774.6,210);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#009FE1").s().p("AkqDIIAAmPIJVAAIAAGPg");
	this.shape_12.setTransform(833.9,210);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#FFFFFF").s().p("Aj3RHMAAAgiNIHvAAMAAAAiNg");
	this.shape_13.setTransform(905,339.4);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#D36240").s().p("AD4RgMAAAgiNInvAAMAAAAiNIgyAAMAAAgimQAAgLAIgHQAHgHAKAAIIhAAQAKAAAIAHQAHAHAAALMAAAAimg");
	this.shape_14.setTransform(905,336.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("Aj3REMAAAgiHIHuAAMAAAAiHg");
	this.shape_15.setTransform(833.6,339.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#009FE1").s().p("AD3RdMAAAgiHInuAAMAAAAiHIgxAAMAAAgigQgBgLAIgHQAHgHAKAAIIgAAQALAAAHAHQAIAHAAALMAAAAigg");
	this.shape_16.setTransform(833.6,336.6);

	this.instance = new lib.numboxlvl_grey("single",0);
	this.instance.setTransform(860.5,190.6,1.171,3.764,0,0,0,-1.5,0.1);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#FFFFFF").s().p("Aj3RHMAAAgiNIHvAAMAAAAiNg");
	this.shape_17.setTransform(964.4,339.4);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#109C81").s().p("AD4RgMAAAgiNInvAAMAAAAiNIgyAAMAAAgimQAAgLAIgHQAHgHAKAAIIhAAQAKAAAIAHQAHAHAAALMAAAAimg");
	this.shape_18.setTransform(964.4,336.9);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#FFFFFF").s().p("Aj3RHMAAAgiNIHvAAMAAAAiNg");
	this.shape_19.setTransform(774.6,339.4);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#E2318B").s().p("AD4RgMAAAgiNInvAAMAAAAiNIgyAAMAAAgimQAAgLAIgHQAHgHAKAAIIhAAQAKAAAIAHQAHAHAAALMAAAAimg");
	this.shape_20.setTransform(774.6,336.9);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f().s("#E2318B").ss(5,1,1).p("ALu/MMAAAA+ZI3bAAMAAAg+Zg");
	this.shape_21.setTransform(135,318.6);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("ArsfNMAAAg+ZIXZAAMAAAA+Zg");
	this.shape_22.setTransform(135,318.6);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f().s("#009FE1").ss(5,1,1).p("ArtfNMAAAg+ZIXbAAMAAAA+Zg");
	this.shape_23.setTransform(289.2,318.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("ArtfNMAAAg+ZIXbAAMAAAA+Zg");
	this.shape_24.setTransform(289.2,318.6);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#000000").s().p("AgyAIIAAgOIBlAAIAAAOg");
	this.shape_25.setTransform(734.1,350.9);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f().s("#D36240").ss(5,1,1).p("ALu/MMAAAA+ZI3aAAMAAAg+Zg");
	this.shape_26.setTransform(454.3,318.6);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("ArtfNMAAAg+ZIXaAAMAAAA+Zg");
	this.shape_27.setTransform(454.3,318.6);

	this.instance_1 = new lib.numboxlvl_grey("single",0);
	this.instance_1.setTransform(362.2,116.8,1.668,5.913,0,0,0,-1.5,0.1);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f().s("#109C81").ss(5,1,1).p("ALufNI3bAAMAAAg+ZIXbAAg");
	this.shape_28.setTransform(609,318.6);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("ArsfNMAAAg+ZIXZAAMAAAA+Zg");
	this.shape_29.setTransform(609,318.6);

	this.addChild(this.shape_29,this.shape_28,this.instance_1,this.shape_27,this.shape_26,this.shape_25,this.shape_24,this.shape_23,this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.instance,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.mcPanel_Tenths,this.mcPanel_Hundredths,this.tfNum_Tenths,this.tfSelect_Tenths,this.tfNum_Hundredths,this.tfSelect_Hundredths,this.tfNum_Tenths2,this.tfNum_Hundredths2,this.pbBreak_Tenths,this.pbMin_Tenths1,this.pbMin_Hundredths1,this.mcWarning,this.mcChangeValue_Hundredths,this.tfNum_Ones,this.tfSelect_Ones,this.tfNum_Ones2,this.mcChangeValue_Ones,this.mcPanel_Ones,this.pbBreak_Ones,this.pbMin_Ones1,this.mcChangeValue_Tenths,this.mcPanel_Tens,this.pbMin_Tens1,this.pbBreak_Tens,this.tfNum_Tens,this.tfSelect_Tens,this.tfNum_Tens2,this.mcChangeValue_Tens,this.shape_4,this.mcDecimal,this.shape_3,this.shape_2,this.shape_1,this.shape,this.mcClone,this.mcInstruction);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(511,383,1026,770);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;