(function (lib, img, cjs, ss) {

var p; // shortcut to reference prototypes

// library properties:
lib.properties = {
	width: 1024,
	height: 768,
	fps: 12,
	color: "#FFFFFF",
	manifest: []
};



// symbols:



(lib.numboxlvl_grey = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#EAEAEA").s().p("Ag7GVIAAspIB2AAIAAMpg");
	this.shape.setTransform(6,40.5);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,12,81);


(lib.mcLeftPanel = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 2
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#00FFFF").ss(5,1,1).p("AypXIMAAAguPMAlTAAAMAAAAuPg");
	this.shape.setTransform(119.5,148);
	this.shape._off = true;

	this.timeline.addTween(cjs.Tween.get(this.shape).wait(1).to({_off:false},0).wait(1));

	// Layer 1
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(204,204,204,0)").s().p("AypXIMAAAguPMAlTAAAMAAAAuPg");
	this.shape_1.setTransform(119.5,148);

	this.timeline.addTween(cjs.Tween.get(this.shape_1).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,238.9,296.1);


(lib.mcDivider_Tenthcopy = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#109C81").ss(5,1,1).p("ARpAAMgjRAAA");
	this.shape.setTransform(112.9,0);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-2.5,-2.5,230.9,5);


(lib.mcDivider_Tenth = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#D36240").ss(5,1,1).p("ARpAAMgjRAAA");
	this.shape.setTransform(112.9,0);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-2.5,-2.5,230.9,5);


(lib.mcDivider_Ten = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#E2318B").ss(5,1,1).p("ARpAAMgjRAAA");
	this.shape.setTransform(112.9,0);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-2.5,-2.5,230.9,5);


(lib.mcDivider_One = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#009FE1").ss(5,2,0,3).p("ARpAAMgjRAAA");
	this.shape.setTransform(112.9,0);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-2.5,-2.5,230.9,5);


(lib.mcDisplay_Thousands = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#94C40C").ss(5,1,1).p("EAKKglIMAAABKRI0TAAMAAAhKRg");
	this.shape.setTransform(222.3,237.8);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("EgKIAlJMAAAhKRIURAAMAAABKRg");
	this.shape_1.setTransform(222.3,237.8);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AA1BmQgGgGAAgLIAAhCIhdAAIAABCQAAALgGAGQgGAGgKAAQgKAAgGgGQgHgGAAgLIAAipQAAgLAHgGQAGgGAKAAQAKAAAGAGQAGAGAAALIAABAIBdAAIAAhAQAAgLAGgGQAGgGAKAAQAKAAAGAGQAGAGABALIAACpQgBALgGAGQgGAGgKAAQgKAAgGgGg");
	this.shape_2.setTransform(892.1,92.2);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#94C40C").s().p("AkpDIIAAmPIJTAAIAAGPg");
	this.shape_3.setTransform(892.1,92.1);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(1,2,0,3).p("AEtlEIgUAAIpFAAAEtFFIgUAAIpFAA");
	this.shape_4.setTransform(890.6,298.6);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Aj3RHMAAAgiNIHvAAMAAAAiNg");
	this.shape_5.setTransform(892.2,221.5);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#94C40C").s().p("AD4RgMAAAgiNInvAAMAAAAiNIgyAAMAAAgimQAAgLAIgHQAHgHAKAAIIhAAQAKAAAIAHQAHAHAAALMAAAAimg");
	this.shape_6.setTransform(892.2,219);

	this.addChild(this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(154.8,-2.5,767.2,480.6);


(lib.mcDecimal = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AgJAMIAAgXIATAAIAAAXg");
	this.shape.setTransform(10,24.8);

	// Layer 2
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("rgba(0,0,0,0.004)").s().p("AhjC9IAAl6IDGAAIAAF6g");
	this.shape_1.setTransform(10,19);

	this.addChild(this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,20,38);


(lib.mcArrow = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF9900").s().p("AgnhVIBPBVIhPBVg");
	this.shape.setTransform(10.8,16);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#00FFFF").s().p("AgnhVIBPBVIhPBVg");
	this.shape_1.setTransform(10.8,16);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#993333").s().p("AgnhVIBPBVIhPBVg");
	this.shape_2.setTransform(10.8,16);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#EAEAEA").s().p("AgnhVIBPBVIhPBVg");
	this.shape_3.setTransform(10.8,16);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).to({state:[{t:this.shape_3}]},1).wait(1));

	// Layer 3
	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AhsCgIAAk/IDZAAIAAE/g");
	this.shape_4.setTransform(10,16);

	this.timeline.addTween(cjs.Tween.get(this.shape_4).wait(4));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(-0.9,0,21.8,32);


(lib.ico_plus = function() {
	this.initialize();

	// hit
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FF9900").s().p("AgSA6IAAgoIgoAAIAAgiIAoAAIAAgpIAlAAIAAApIAoAAIAAAiIgoAAIAAAog");
	this.shape.setTransform(-0.8,-0.8);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-6.8,-6.6,12,11.8);


(lib.numdotlvl_yellow = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAVASIAAgcIgGAAIAAgEIADAAIABgBIACgCIAEAAIAAAjgAAEASIAAgFIAFAAIAAAFgAgTARQgDgCgBgDQgBgDAAgFIAAgIIABgHQABgDADgCQADgBADAAQAEAAADABQACACACADQABADAAAEIAAAIQAAAIgDADQgDADgFAAQgEAAgDgBgAgIANIACgDIABgGIAAgHIgBgFQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBIgFgBIgEABQAAAAAAABQgBAAAAAAQAAABgBAAQAAABAAAAIgBAGIAAAHIABAGQAAAAAAABQABAAAAABQAAAAABABQAAAAABAAQAAAAABABQAAAAAAAAQABAAABAAQAAAAABAAIAEgBg");
	this.shape.setTransform(-0.2,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D36240").s().p("AAAA5QgWAAgSgRQgQgRAAgXQAAgWAQgSQASgQAWAAQAXAAARAQQARASAAAWQAAAXgRARQgRARgXAAIAAAAgAASgQIgCABIgCABIAAAEIAFAAIAAAcIAFAAIAAgjIgFAAIgBABgAACASIAFAAIAAgGIgFAAgAgUgQQgEABgBAEIgBAHIAAAIQAAAFABADQABADAEACQACABAEAAQAFAAADgDQADgEABgHIAAgIQAAgEgCgDQgBgEgDgBQgDgCgEABQgDgBgCACgAgOAOQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQgBgBAAgBIgBgGIAAgGIABgGQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIADgBIAFABQAAAAABABQAAAAABABQAAAAAAABQAAAAABABIAAAFIAAAGIAAAGIgDAEIgDABIgBAAg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#982E0F").s().p("AgrAsQgSgSAAgaQAAgZASgSQASgSAZAAQAaAAASASQASASAAAZQAAAagSASQgSASgaAAQgZAAgSgSgAgogoQgQASAAAWQAAAXAQARQASARAWAAQAXAAARgRQARgRAAgXQAAgWgRgSQgRgQgXAAIAAAAQgXAAgRAQg");

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-6.2,-6.2,12.5,12.5);


(lib.numdotlvl_red = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAjASIAAgcIgFAAIAAgEIACAAIACgBIACgCIAEAAIAAAjgAAGARQgDgCgBgDQgCgDAAgFIAAgIIACgHQABgDADgCQADgBADAAQADAAADABQADACACADQABADAAAEIAAAIQAAAIgDADQgDADgFAAQgFAAgCgBgAAQANIADgDIABgGIAAgHIgBgFQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAgBgBIgEgBIgEABQAAAAgBABQAAAAAAAAQgBABAAAAQAAABgBAAIAAAGIAAAHIAAAGQABAAAAABQAAAAABABQAAAAABABQAAAAAAAAQABAAAAABQABAAAAAAQABAAAAAAQABAAABAAIADgBgAgJASIAAgFIAFAAIAAAFgAgiARQgDgCgBgDQgBgDAAgFIAAgIIABgHQACgDACgCQADgBADAAQAEAAADABQADACABADQABADAAAEIAAAIQAAAIgDADQgDADgFAAQgEAAgDgBgAgXANIADgDIAAgGIAAgHIAAgFQgBgBAAAAQAAgBAAAAQgBgBAAAAQgBAAAAgBIgFgBIgDABQgBAAAAABQgBAAAAAAQAAABAAAAQgBABAAAAIgBAGIAAAHIABAGQAAAAABABQAAAAAAABQABAAAAABQAAAAABAAQAAAAABABQAAAAABAAQAAAAABAAQAAAAABAAIAEgBg");
	this.shape.setTransform(-0.1,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#035444").s().p("AgrAsQgSgSAAgaQAAgZASgSQASgSAZAAQAaAAASASQASASAAAZQAAAagSASQgSASgaAAQgZAAgSgSgAgogoQgQASAAAWQAAAXAQARQASARAWAAQAXAAARgRQARgRAAgXQAAgWgRgSQgRgQgXAAIAAAAQgXAAgRAQg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#109C81").s().p("AAAA5QgWAAgSgRQgQgRAAgXQAAgWAQgSQASgQAWAAQAXAAARAQQARASAAAWQAAAXgRARQgRARgXAAIAAAAgAAhgQIgCABIgDABIAAAEIAGAAIAAAcIAEAAIAAgjIgDAAIgCABgAgKASIAEAAIAAgGIgEAAgAgjgQQgDABgCAEIgBAHIAAAIQAAAFACADQABADADACQADABAEAAQAFAAADgDQADgEAAgHIAAgIQAAgEgBgDQgCgEgDgBQgDgCgDABQgDgBgDACgAgcAOQgBAAgBAAQAAAAgBAAQAAAAgBgBQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIgBgGIAAgGIABgGQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIAEgBIAEABQABAAAAABQABAAAAABQAAAAABABQAAAAAAABIAAAFIAAAGIAAAGIgDAEIgCABIgBAAg");

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-6.2,-6.2,12.5,12.5);


(lib.numdotlvl_purple = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AACARQgCgCAAgDQgBgDAAgFIAAgIIABgHQAAgDACgCQADgBADAAQAEAAADABQACACACADQABADAAAEIAAAIQAAAIgDADQgDADgFAAQgEAAgDgBgAANANIACgDIABgGIAAgHIgBgFQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBIgFgBIgEABQAAAAAAABQgBAAAAAAQAAABgBAAQAAABAAAAIgBAGIAAAHIABAGQAAAAAAABQABAAAAABQAAAAABABQAAAAABAAQAAAAABABQAAAAAAAAQABAAABAAQAAAAABAAIAEgBgAgOASIAAgcIgFAAIAAgEIACAAIACgBIACgCIAEAAIAAAjg");
	this.shape.setTransform(-0.1,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#E2318B").s().p("AgoApQgQgSAAgXQAAgWAQgSQASgQAWAAQAXAAASAQQAQASAAAWQAAAXgQASQgSAQgXAAQgWAAgSgQg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#B1045C").s().p("AgrAsQgSgSAAgaQAAgZASgSQASgSAZAAQAaAAASASQASASAAAZQAAAagSASQgSASgaAAQgZAAgSgSgAgogoQgQASAAAWQAAAXAQASQASAQAWAAQAXAAASgQQAQgSAAgXQAAgWgQgSQgSgQgXAAQgWAAgSAQg");

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-6.2,-6.2,12.5,12.5);


(lib.numdotlvl_pink = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAAASIAAgcIgDAAIAAgEIACAAIABgBIAAgCIAFAAIAAAjg");
	this.shape.setTransform(-0.1,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#009FE1").s().p("AAAA5QgWAAgSgRQgQgRAAgXQAAgWAQgSQASgQAWAAQAXAAARAQQARASAAAWQAAAXgRARQgRARgXAAIAAAAgAgBgQIgBABIgDABIAAAEIAFAAIAAAcIADAAIAAgjIgDAAIgBABg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#006D9A").s().p("AgrAsQgSgSAAgaQAAgZASgSQASgSAZAAQAaAAASASQASASAAAZQAAAagSASQgSASgaAAQgZAAgSgSgAgogoQgQASAAAWQAAAXAQARQASARAWAAQAXAAARgRQARgRAAgXQAAgWgRgSQgRgQgXAAIAAAAQgXAAgRAQg");

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-6.2,-6.2,12.5,12.5);


(lib.numdotlvl_darkblue = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AAVASIAAgcIgGAAIAAgEIADAAIABgBIACgCIAEAAIAAAjgAAEASIAAgFIAFAAIAAAFgAgTARQgDgCgBgDQgBgDAAgFIAAgIIABgHQABgDADgCQADgBADAAQAEAAADABQACACACADQABADAAAEIAAAIQAAAIgDADQgDADgFAAQgEAAgDgBgAgIANIACgDIABgGIAAgHIgBgFQAAgBAAAAQAAgBgBAAQAAgBAAAAQgBAAAAgBIgFgBIgEABQAAAAAAABQgBAAAAAAQAAABgBAAQAAABAAAAIgBAGIAAAHIABAGQAAAAAAABQABAAAAABQAAAAABABQAAAAABAAQAAAAABABQAAAAAAAAQABAAABAAQAAAAABAAIAEgBg");
	this.shape.setTransform(-0.2,0);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#D36240").s().p("AAAA5QgWAAgSgRQgQgRAAgXQAAgWAQgSQASgQAWAAQAXAAARAQQARASAAAWQAAAXgRARQgRARgXAAIAAAAgAASgQIgCABIgCABIAAAEIAFAAIAAAcIAFAAIAAgjIgFAAIgBABgAACASIAFAAIAAgGIgFAAgAgUgQQgEABgBAEIgBAHIAAAIQAAAFABADQABADAEACQACABAEAAQAFAAADgDQADgEABgHIAAgIQAAgEgCgDQgBgEgDgBQgDgCgEABQgDgBgCACgAgOAOQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAQgBgBAAgBIgBgGIAAgGIABgGQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAABAAIADgBIAFABQAAAAABABQAAAAABABQAAAAAAABQAAAAABABIAAAFIAAAGIAAAGIgDAEIgDABIgBAAg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#982E0F").s().p("AgrAsQgSgSAAgaQAAgZASgSQASgSAZAAQAaAAASASQASASAAAZQAAAagSASQgSASgaAAQgZAAgSgSgAgogoQgQASAAAWQAAAXAQARQASARAWAAQAXAAARgRQARgRAAgXQAAgWgRgSQgRgQgXAAIAAAAQgXAAgRAQg");

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-6.2,-6.2,12.5,12.5);


(lib.numdotlvl_blue = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AARARQgDgCgBgDQgCgDABgFIAAgIIABgHQABgDADgCQACgBAEAAQAEAAADABQACACABADQACADAAAEIAAAIQAAAIgDADQgDADgGAAQgDAAgDgBgAAcANIACgDIABgGIAAgHIgBgFQAAgBAAAAQgBgBAAAAQAAgBgBAAQAAAAAAgBIgFgBIgEABQAAAAgBABQAAAAAAAAQgBABAAAAQAAABgBAAIgBAGIAAAHIABAGQABAAAAABQAAAAABABQAAAAABABQAAAAABAAQAAAAAAABQABAAAAAAQABAAAAAAQABAAAAAAIAFgBgAgLARQgCgCgBgDQgCgDAAgFIAAgIIABgHQABgDADgCQADgBAEAAQADAAABABQACACACADQACADgBAEIAAAIQAAAIgCADQgDADgEAAQgEAAgDgBgAAAANIABgDIAAgGIAAgHIAAgFQgBgBAAAAQAAgBAAAAQAAgBAAAAQAAAAAAgBIgEgBIgFABQAAAAAAABQgBAAAAAAQAAABAAAAQgBABAAAAIgBAGIAAAHIABAGQAAAAABABQAAAAAAABQABAAAAABQABAAAAAAQAAAAABABQAAAAABAAQAAAAABAAQAAAAABAAIAEgBgAgdASIAAgcIgFAAIAAgEIADAAIABgBIACgCIAEAAIAAAjg");

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#608300").s().p("AgrAsQgSgSAAgaQAAgZASgSQASgSAZAAQAaAAASASQASASAAAZQAAAagSASQgSASgaAAQgZAAgSgSgAgogoQgQASAAAWQAAAXAQASQASAQAWAAQAXAAASgQQAQgSAAgXQAAgWgQgSQgSgQgXAAQgWAAgSAQg");

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#94C40C").s().p("AgoApQgQgSAAgXQAAgWAQgSQASgQAWAAQAXAAASAQQAQASAAAWQAAAXgQASQgSAQgXAAQgWAAgSgQgAARgQQgDABgCAEIgBAHIAAAIQAAAFABADQACADADACQACABAEAAQAGAAADgDQADgEAAgHIAAgIQgBgEgBgDQgCgEgCgBQgDgCgDABQgEgBgCACgAgLgQQgDABgCAEIgBAHIAAAIQABAFABADQABADADACQACABAEAAQAFAAACgDQADgEAAgHIAAgIQAAgEgCgDQgBgEgCgBQgBgCgEABQgDgBgDACgAgfgQIgBABIgDABIAAAEIAGAAIAAAcIAEAAIAAgjIgDAAIgDABgAAXAOQgBAAAAAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQAAAAgBgBQAAAAgBAAQAAgBAAAAQgBgBAAgBIgBgGIAAgGIABgGQAAgBABAAQAAgBAAAAQAAAAABgBQAAAAAAAAIAFgBIAEABQABAAAAABQAAAAABABQAAAAAAABQAAAAAAABIABAFIAAAGIgBAGIgCAEIgDABIgBAAgAgFAOQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAQAAgBAAgBIgCgGIAAgGIACgGQAAgBAAAAQAAgBABAAQAAAAAAgBQABAAAAAAIAEgBIAFABQAAAAAAABQAAAAAAABQAAAAAAABQAAAAAAABIAAAFIAAAGIAAAGIAAAEIgDABIgCAAg");

	this.addChild(this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-6.2,-6.2,12.5,12.5);


(lib.pbPlus = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.instance = new lib.ico_plus("single",0);
	this.instance.setTransform(11.4,11.3);

	this.shape = new cjs.Shape();
	this.shape.graphics.f("#00FFFF").s().p("AgSA6IAAgoIgpAAIAAgiIApAAIAAgpIAlAAIAAApIAoAAIAAAiIgoAAIAAAog");
	this.shape.setTransform(10.5,10.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#993333").s().p("AgSA6IAAgoIgpAAIAAgiIApAAIAAgpIAlAAIAAApIAoAAIAAAiIgoAAIAAAog");
	this.shape_1.setTransform(10.5,10.5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#EAEAEA").s().p("AgSA6IAAgoIgpAAIAAgiIApAAIAAgpIAlAAIAAApIAoAAIAAAiIgoAAIAAAog");
	this.shape_2.setTransform(10.5,10.5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance}]}).to({state:[{t:this.shape}]},1).to({state:[{t:this.shape_1}]},1).to({state:[{t:this.shape_2}]},1).wait(1));

	// Layer 3
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AhoBoIAAjQIDQAAIAADQg");
	this.shape_3.setTransform(10.5,10.5);

	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(4));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,21,21);


(lib.mcInstruction = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AGpBzIAehHIgphoIAkAAIAWBDIAahDIAkAAIhLCvgAXDAaIAAg4IgXAAIAAgdIAXAAIAAg3IAgAAIAAA3IAVAAIAAAdIgVAAIAAA1QAOAGAHgHIAAAYQgEAIgNABIgFAAQgHADgGAAQgSAAAAgggAUtAaIAAg4IgXAAIAAgdIAXAAIAAg3IAfAAIAAA3IAXAAIAAAdIgXAAIAAA1QAPAGAIgHIAAAYQgFAIgNABIgFAAQgHADgGAAQgSAAAAgggAEdAaIAAg4IgXAAIAAgdIAXAAIAAg3IAgAAIAAA3IAVAAIAAAdIgVAAIAAA1QAOAGAHgHIAAAYQgDAIgOABIgFAAQgHADgGAAQgSAAAAgggAhJAaIAAg4IgXAAIAAgdIAXAAIAAg3IAgAAIAAA3IAVAAIAAAdIgVAAIAAA1QAOAGAHgHIAAAYQgDAIgOABIgFAAQgHADgGAAQgSAAAAgggA4bAaIAAg4IgXAAIAAgdIAXAAIAAg3IAfAAIAAA3IAXAAIAAAdIgXAAIAAA1QAPAGAIgHIAAAYQgFAIgNABIgFAAQgHADgGAAQgSAAAAgggA+XAaIAAg4IgXAAIAAgdIAXAAIAAg3IAgAAIAAA3IAVAAIAAAdIgVAAIAAA1QAOAGAHgHIAAAYQgEAIgNABIgFAAQgHADgGAAQgSAAAAgggAKmABIAAg8IAgAAIAAA5QACAdARAAQANAAAFgIQADgDABgUIAAg3IAgAAIAAByIgfAAIAAgJQgKAJgTAAIgGABQgnAAAAg3gAkRAOIAjAAQAIANALAAQAMgBAAgHQgIgIgNgDQgngIAAgYQAIgjAnAAQAtAAACAkIggAAQgBgJgPAAQgNACAAAGQgDADAcAJQAkAIAEAVQgJAmgqAAIgFAAQgqAAgGgpgEAhwAA3IAAgfIAkAAIAAAfgEAg9AA3IAAgNQgNANgWAAQg6gIAAgwQAKg6AwAAQAUAAANAKIAAhBIAfAAIAACpgEAgAgACQAFAeAaAAQAegFAAgYQgEgegbAAQgeAFAAAYgAexA3IAAgNQgOANgUAAQg7gIAAgwQAJg6AxAAQAUAAAMAKIAAhBIAhAAIAACpgAd0gCQAFAeAZAAQAegFAAgYQgEgegaAAQgeAFAAAYgAcmA3IAAgNQgNANgXAAQg6gHAAgxQAIg6AzAAQAUAAAPAMIAAgKIAcAAIAABwgAboAAQADAbAbAAQAfgEAAgXQgFgfgaAAQgeAEAAAbgAYHgBQALg6AzAAQA+AJAAAyQgLA3gzAAQg9gKgBgugAYngBQAGAcAYAAQAegEAAgYQgFgegZAAQgeAFAAAZgATkA3IAAg3QgCgfgRAAQgMABgFAIQgFADAAAVIAAA1IgfAAIAAhyIAdAAIAAAKQAMgLARAAQAZABAMAQQAIAKAAAdIAAA7gARpA3IAAgNQgMANgXAAQg6gHAAgxQAIg6AzAAQAUAAAOAMIAAgKIAdAAIAABwgAQsAAQADAbAcAAQAdgEAAgXQgDgfgbAAQgeAEAAAbgAPDA3IgUhAIgUBAIgUAAIgqhzIAjAAIARA8IASg8IAZAAIARA8IASg8IAhAAIgpBzgAIfgBQALg6AzAAQA+AJAAAyQgLA3gzAAQg9gKgBgugAI/gBQAGAcAYAAQAegEAAgYQgFgegZAAQgeAFAAAZgADbA3IAAgNQgMANgXAAQg6gHAAgxQAIg6AzAAQAUAAAOAMIAAgKIAdAAIAABwgACeAAQADAbAcAAQAegEAAgXQgEgfgbAAQgeAEAAAbgABKA3IAAg3QABgcgUAAQgWgFAAAhIAAA3IgfAAIAAipIAfAAIAABBQALgIAPAAQAvgDgBA3IAAA8gAlGA3IAAipIAgAAIAACpgAl7A3IAAgNQgNANgWAAQg6gHAAgxQAIg6AzAAQAVAAANAMIAAgKIAeAAIAABwgAm4AAQADAbAcAAQAdgEAAgXQgEgfgaAAQgeAEAAAbgAoGA3IAAg8QgCgagQAAQgVgHABAmIAAA3IggAAIAAg8QAAgagTAAQgUgHABAmIAAA3IghAAIAAhyIAeAAIAAAJQAKgKAQAAQAVAAAMAQQANgQAXAAQAwABAAAzIAAA/gArKA3IAAhyIAgAAIAABygAtWgBQAKg6AzAAQAsgBAQAsIgjAAQgIgPgRAAQgdAEAAAaQAEAcAaAAQAOABAKgPIAjAAQgSAqgpAAQg+gJAAgvgAvggBQAKg6AzAAQA8AIAAAzIgCALIhVAAQAHAQAVAAQAFADATgHIAhAAQgVAggkAAQg+gIAAgwgAuEgKQgGgWgYAAQgWABgHAVIA7AAIAAAAgAwPA3IAAgNQgNANgWAAQg6gIAAgwQAKg6AwAAQAUAAANAKIAAhBIAfAAIAACpgAxMgCQAFAeAaAAQAegFAAgYQgEgegbAAQgeAFAAAYgA0tgBQALg6AzAAQA+AJAAAyQgLA3gzAAQg+gKAAgugA0NgBQAGAcAYAAQAegEAAgYQgFgegZAAQgeAFAAAZgA10A3IgThAIgUBAIgTAAIgrhzIAjAAIASA8IARg8IAZAAIAQA8IATg8IAhAAIgpBzgA7AA3IAAhyIAdAAIAAAIQAHgJAPAAIACAAQAOACADADIAAAeQgIgFgJAAQgWAAABAYIAAA9gA9QgBQAKg6AzAAQA8AIAAAzIgBALIhWAAQAHAQAVAAQAFADATgHIAhAAQgVAggkAAQg+gIAAgwgA70gKQgGgWgYAAQgWABgHAVIA7AAIAAAAgA/hA3IAAg3QgBgfgRAAQgMABgGAIQgEADAAAVIAAA1IggAAIAAhyIAeAAIAAAKQAMgLARAAQAZABAMAQQAJAKAAAdIAAA7gEgiSAA3IAAipIBVAAIAAAjIg1AAIAAAiIAyAAIAAAjIgyAAIAAAfIA1AAIAAAigArKhTIAAgfIAgAAIAAAfg");
	this.shape.setTransform(219.7,11.4);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("APdBVIAAggIAjAAIAAAggAOnBVIAAgNQgIAHgIADQgIADgLAAQgQAAgNgIQgOgHgHgNQgIgNAAgRQAAgQAIgLQAHgOAOgHQANgIAQAAQAJAAAJACQAIADAGAFIAAhAIAgAAIAACogAN5AAQgHAEgEAHQgEAHAAAIQAAAJAEAHQAEAHAHAEQAHAEAIAAQAJAAAHgEQAGgEAEgHQAEgGAAgJQAAgJgEgHQgEgHgGgDQgIgCgIgBQgJABgGABgAMYBVIAAgNQgIAHgIADQgJADgKAAQgQAAgNgIQgOgHgHgNQgIgNABgRQgBgQAIgLQAHgOAOgHQANgIAQAAQAJAAAJACQAIADAGAFIAAhAIAfAAIAACogALqAAQgHAEgEAHQgEAHAAAIQAAAJAEAHQAEAHAHAEQAHAEAIAAQAJAAAGgEQAHgEAEgHQAEgGAAgJQAAgJgEgHQgEgHgHgDQgGgCgJgBQgJABgGABgAKIBVIAAgNQgHAHgJADQgIADgLAAQgQAAgNgIQgOgHgHgNQgIgNABgRQgBgRAIgLQAHgNAOgIQANgHARAAQAKAAAJADQAIADAHAGIAAgKIAdAAIAABwgAJTAFQgIAJAAAOQAAANAIAIQAJAHANABQAKAAAGgEQAHgEADgHQAEgGAAgJQAAgIgEgHQgEgHgHgEQgGgCgJAAQgNAAgJAGgAGJBNQgOgIgIgNQgIgNgBgQQABgQAIgLQAIgOAOgHQAOgIARAAQARAAAOAIQAOAHAIAOQAIALAAARQAAAPgIANQgJANgOAIQgNAIgRAAQgRAAgOgIgAGZABQgHAEgEAGQgDAHgBAIQABAJADAHQAEAHAHAEQAGAEAJAAQAIAAAHgEQAGgEAFgHQADgHAAgIQAAgJgDgGQgFgHgGgEQgHgCgIAAQgJAAgGACgAoRBNQgNgIgJgNQgIgNAAgQQAAgRAIgLQAIgNAOgIQANgHARAAQAOAAALAEQAMAFAIAKQAJAJAGAMIgjAAQgFgHgFgEQgGgBgJAAQgNAAgHAGQgJAIAAAOQABAIADAHQAEAHAHAEQAGAEAJAAQAHAAAGgDQAGgEAFgHIAjAAQgJAVgPAKQgOALgVAAQgRAAgOgIgAqZBNQgOgHgIgNQgJgNAAgRQABgQAHgMQAJgNAOgHQANgIARAAQARAAAOAIQAOAHAHAOQAIALAAARIAAAGIgBAGIhVAAQADAIAHAEQAHAFAKAAIAIAAIAHgCIAJgDIAhAAQgEANgKAHQgIAHgLADQgLADgMAAQgSAAgOgIgApcASQgDgLgIgGQgHgEgMAAQgKAAgIAEQgHAGgEALIA7AAIAAAAgArtBVIAAioIAgAAIAACogAteBNQgOgHgJgNQgIgNAAgRQAAgQAIgMQAIgNAOgHQANgIASAAQARAAAOAIQANAHAIAOQAHALABARIgBAGIgBAGIhVAAQADAIAHAEQAIAFAKAAIAHAAIAHgCIAJgDIAiAAQgFANgJAHQgJAHgLADQgLADgMAAQgRAAgOgIgAshASQgEgLgHgGQgIgEgLAAQgLAAgHAEQgIAGgDALIA7AAIAAAAgAviBPQgLgHgJgMQgHgMgCgRIAkAAQAAALAHAEQAFAFAJAAQAKAAAFgFQAFgEAAgIQgBgDgDgDIgHgHIgIgEIgDgCIgCgBIgBgBIgEgCIgKgFQgKgGgIgEQgGgGgEgIQgEgHABgLQAAgNAGgLQAHgLALgGQAMgHAOAAQAOAAALAGQAMAGAHALQAHAMABAQIgjAAQgBgJgFgEQgFgEgGAAQgHAAgEACQgDADgDADQgCADAAADIABAFIAEAFIAJAGIARAJQAVALALAIQAMALAAAMQAAAQgHAMQgIAMgMAHQgMAHgRAAQgPAAgNgGgAE5BUIgKgEQgFgCgDgGQgEgGAAgKIAAg4IgXAAIAAgdIAXAAIAAg2IAgAAIAAA2IAVAAIAAAdIgWAAIAAA0QAAAEADABQADABAEgBIAHgCQADgBACgCIAAAXIgDADIgGAEQgEACgEAAIgFAAIgJAAgAmABUIgKgEQgFgCgEgGQgEgGAAgKIAAg4IgWAAIAAgdIAWAAIAAg2IAgAAIAAA2IAWAAIAAAdIgWAAIAAA0QAAAEACABQADABAEgBIAIgCQADgBABgCIAAAXIgDADIgGAEQgDACgFAAIgEAAIgJAAgACdgWIAHgMIAEgIIACgGIABgEIgPAAIAAgfIAjAAIAAAbIgDAMIgFAJIgEAHIgFAGgABugWIAIgMIADgIIACgGIABgEIgOAAIAAgfIAjAAIAAAbIgFAMIgDAJIgFAHIgEAGgAjdgWIAAgcIAFgMIAEgJIAEgGIAEgGIASAAIgIAMIgDAIIgCAGIgBAEIAOAAIAAAfgAkLgWIAAgcIAEgMIAFgJIAEgGIAFgGIARAAIgIAMIgDAIIgCAGIgBAEIAOAAIAAAfg");
	this.shape_1.setTransform(101.1,7.9);

	this.instance = new lib.ico_plus("single",0);
	this.instance.setTransform(98.3,8.9,1.187,1.186);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("Ah7B8IAAj3ID3AAIAAD3g");
	this.shape_2.setTransform(97.3,7.9);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#000000").s().p("AGEByIAAitIAcAAIAAALQAIgFAIgDQAJgDAKAAQAQAAANAIQANAHAIAOQAHANAAARQAAAQgIAOQgGANgOAHQgNAJgQgBQgKABgHgDQgJgCgGgFIAABBgAGwgaQgHAEgDAHQgFAHAAAIQAAAHAFAIQAEAHAGAEQAHAEAIAAQAJgBAGgDQAHgEAEgHQAEgHAAgIQAAgIgEgHQgEgHgHgEQgGgEgJAAQgIAAgHAEgAhYBoQgQgKgIgTIAjAAQAFAHAHACQAGADAJAAQAKAAAHgDQAGgEACgFQACgHAAgHIABgPQgIAHgIACQgHACgLAAQgRgBgMgIQgNgHgHgNQgIgOABgPQAAgQAHgNQAHgNANgIQAMgHARgBQALAAAIADQAJADAGAGIAAgKIAcAAIAABYQAAASgBAPQgCAPgDAMQgFAKgNAHQgMAGgVAAQgWAAgPgKgAhJgWQgIAIAAAOQAAANAIAHQAHAIAOAAQANAAAIgIQAIgIAAgMQgBgOgHgIQgIgIgNAAQgOAAgHAIgAELAqQgMgNAAgcIAAg8IAgAAIAAA5QAAAMACAGQACAHAFACQAEACAFAAQAGAAAFgDQAEgCADgDQACgEABgFIABgOIAAg3IAgAAIAAByIgeAAIAAgJQgHAFgGACQgIACgJAAIgBAAQgUAAgLgNgAdgA3IAAggIAjAAIAAAggAbwAwQgOgIgHgNQgJgNAAgPQAAgQAIgNQAIgNAOgIQAOgIARAAQARAAAOAIQANAIAHANQAIAOAAAQIAAAEIgBAHIhUAAQACAHAIAEQAGAFALAAIAHAAIAHgCIAJgDIAiAAQgFAOgJAGQgIAIgMACQgLADgLAAQgTAAgOgHgAcugKQgDgKgIgHQgHgFgMAAQgKAAgIAFQgHAGgEALIA7AAIAAAAgAafA3IAAg8QAAgKgCgGQgDgGgEgCQgEgCgGABQgGgBgEADQgFADgCAGQgDAIABALIAAA3IggAAIAAg8QAAgKgCgGQgDgGgEgCQgEgCgGABQgGgBgFADQgEADgDAGQgCAIAAALIAAA3IgeAAIAAhyIAdAAIAAAJQAEgFAHgCQAHgDAIABQALAAAIADQAIAEAGAIQAGgIAJgEQAJgDALAAQAXAAAMAMQANANAAAaIAAA/gAXcA3IAAgNQgHAHgIADQgIADgLAAQgRAAgNgHQgNgIgIgNQgHgNAAgPQAAgRAHgNQAIgNANgHQANgIASAAQAKAAAJADQAHADAHAGIAAgKIAeAAIAABwgAWogWQgIAIAAAOQAAALAIAIQAIAIANAAQAKAAAHgEQAGgEAEgHQAEgGgBgHQAAgIgDgHQgEgHgHgEQgHgEgJAAQgNAAgIAJgAVLA3IAAg3QAAgMgCgIQgCgGgFgDQgDgCgHABQgFgBgFACQgEADgDAFQgCACgBAGIgBAPIAAA1IggAAIAAhyIAeAAIAAAKQAHgFAGgDQAIgDAIABQAMAAAJAEQAJAEAHAJIAEAJQADAGAAAGQABAIAAAJIAAA7gASUAwQgOgIgHgNQgJgNAAgPQAAgQAIgNQAIgNAOgIQAOgIARAAQARAAAOAIQANAIAHANQAIAOAAAQIAAAEIgBAHIhVAAQAEAHAHAEQAGAFALAAIAHAAIAHgCIAJgDIAiAAQgFAOgJAGQgJAIgLACQgLADgLAAQgTAAgOgHgATSgKQgDgKgIgHQgHgFgMAAQgKAAgIAFQgIAGgDALIA7AAIAAAAgAQfA3IAAhyIAcAAIAAAJQAFgGAFgCQAFgCAIABIACAAIAGABIAGABIAFACIAAAeIgJgEIgIgBQgLABgGAGQgFAFAAAMIAAA9gAOwA3IAAgNQgIAHgHADQgJADgKAAQgRAAgNgHQgNgIgIgNQgHgNAAgPQAAgQAHgNQAIgNANgIQANgIARAAQAJAAAIACQAJADAFAFIAAhAIAgAAIAACogAOCgcQgGAFgFAHQgDAGAAAIQAAAHADAHQAFAHAHAEQAGAFAJAAQAIAAAHgFQAHgDADgIQAEgGABgHQgBgJgEgGQgDgIgHgDQgHgEgJAAQgIAAgHADgAMgA3IAAg3QAAgMgDgIQgCgGgEgDQgFgCgGABQgFgBgFACQgEADgDAFQgCACgBAGIgBAPIAAA1IgfAAIAAhyIAdAAIAAAKQAHgFAGgDQAIgDAIABQAMAAAJAEQAKAEAFAJIAGAJQABAGABAGQABAIgBAJIAAA7gAKhA3IAAgNQgIAHgHADQgJADgKAAQgSAAgNgHQgNgIgHgNQgIgNAAgPQAAgRAIgNQAHgNANgHQAOgIARAAQALAAAIADQAIADAHAGIAAgKIAdAAIAABwgAJsgWQgIAIAAAOQAAALAIAIQAJAIANAAQAJAAAHgEQAHgEAEgHQADgGAAgHQAAgIgEgHQgEgHgGgEQgIgEgIAAQgNAAgJAJgACSAvQgNgHgIgNQgJgOAAgOQAAgQAJgNQAHgNAOgIQAOgIARAAQARAAAPAIQAOAIAHANQAJANgBARQAAAOgIANQgIANgOAHQgNAIgSAAQgRAAgOgIgACjgbQgHAEgEAHQgEAHgBAHQABAIAEAGQAEAHAHAEQAGAEAIAAQAJAAAGgEQAHgEAEgHQAEgHAAgGQAAgIgEgHQgEgHgHgEQgGgEgJAAQgIAAgGAEgAAfA3IAAhyIAdAAIAAAJQAEgGAFgCQAGgCAHABIACAAIAHABIAGABIAEACIAAAeIgJgEIgIgBQgLABgGAGQgEAFAAAMIAAA9gAjcAwQgOgIgIgNQgJgNABgPQAAgQAIgNQAHgNAOgIQAOgIARAAQASAAANAIQANAIAIANQAHAOABAQIgBAEIAAAHIhVAAQADAHAHAEQAHAFALAAIAHAAIAGgCIAJgDIAiAAQgEAOgKAGQgIAIgMACQgLADgLAAQgSAAgOgHgAifgKQgDgKgHgHQgIgFgLAAQgLAAgHAFQgIAGgEALIA7AAIAAAAgAlSA3IAAhyIAdAAIAAAJQAFgGAEgCQAGgCAHABIACAAIAHABIAGABIAFACIAAAeIgJgEIgJgBQgLABgGAGQgEAFgBAMIAAA9gAn4AvQgOgHgIgNQgIgOgBgOQABgQAIgNQAIgNAOgIQAOgIARAAQARAAAOAIQAOAIAIANQAIANAAARQAAAOgIANQgJANgOAHQgNAIgRAAQgRAAgOgIgAnogbQgHAEgEAHQgDAHgBAHQABAIADAGQAEAHAHAEQAGAEAJAAQAIAAAHgEQAGgEAFgHQADgHAAgGQAAgIgDgHQgFgHgGgEQgHgEgIAAQgJAAgGAEgA2UAvQgNgHgJgNQgIgNAAgPQAAgQAIgNQAIgOAOgHQANgIARAAQAOAAALAEQAMAGAIAJQAJAKAGAOIgjAAQgFgIgFgEQgGgDgJAAQgNAAgHAJQgJAHAAAOQABAGADAHQAEAHAHAEQAGAEAJAAQAHAAAGgDQAGgDAFgIIAjAAQgJAVgPALQgOAKgVAAQgRAAgOgIgA4cAwQgOgIgIgNQgJgNAAgPQABgQAHgNQAJgNAOgIQANgIARAAQARAAAOAIQAOAIAHANQAIAOAAAQIAAAEIgBAHIhVAAQADAHAHAEQAHAFAKAAIAIAAIAHgCIAJgDIAhAAQgEAOgKAGQgIAIgLACQgLADgMAAQgSAAgOgHgA3fgKQgDgKgIgHQgHgFgMAAQgKAAgIAFQgHAGgEALIA7AAIAAAAgA5wA3IAAioIAgAAIAACogA7hAwQgOgIgJgNQgIgNAAgPQAAgQAIgNQAIgNAOgIQANgIASAAQARAAAOAIQANAIAIANQAHAOABAQIgBAEIgBAHIhVAAQADAHAHAEQAIAFAKAAIAHAAIAHgCIAJgDIAiAAQgFAOgJAGQgJAIgLACQgLADgMAAQgRAAgOgHgA6kgKQgEgKgHgHQgIgFgLAAQgLAAgHAFQgIAGgDALIA7AAIAAAAgA9lAxQgLgHgJgMQgHgMgCgQIAkAAQAAAKAHAEQAFAGAJAAQAKgBAFgFQAFgEAAgIQgBgDgDgBIgHgGIgIgFIgDgCIgCgBIgBAAIgEgCIgKgGQgKgGgIgFQgGgGgEgJQgEgHABgLQAAgNAGgLQAHgLALgGQAMgGAOAAQAOAAALAFQAMAHAHAKQAHAMABAQIgjAAQgBgJgFgEQgFgEgGAAQgHAAgEADQgDACgDADQgCADAAADIABAFIAEAFIAJAHIARAJQAVAKALAKQAMAMAAAKQAAAPgHAMQgIAMgMAHQgMAHgRAAQgPAAgNgGgApIA2IgKgEQgFgCgDgGQgEgGAAgKIAAg4IgXAAIAAgdIAXAAIAAg2IAgAAIAAA2IAVAAIAAAdIgWAAIAAA0QAAAEADABQADABAEAAIAHgDQADgBACgCIAAAYIgDACIgGAEQgEACgEAAIgFABIgJgBgA0DA2IgKgEQgFgCgEgGQgEgGAAgKIAAg4IgWAAIAAgdIAWAAIAAg2IAgAAIAAA2IAWAAIAAAdIgWAAIAAA0QAAAEACABQADABAEAAIAIgDQADgBABgCIAAAYIgDACIgGAEQgDACgFAAIgEABIgJgBgArkg0IAHgMIAEgIIACgFIABgFIgPAAIAAgeIAjAAIAAAbIgDALIgFAJIgEAHIgFAGgAsTg0IAIgMIADgIIACgFIABgFIgOAAIAAgeIAjAAIAAAbIgFALIgEAJIgEAHIgEAGgAxgg0IAAgbIAFgNIAEgJIAEgFIAEgGIASAAIgIALIgDAIIgCAGIgBAEIAOAAIAAAfgAyOg0IAAgbIAEgNIAFgJIAEgFIAFgGIARAAIgIALIgDAIIgCAGIgBAEIAOAAIAAAfg");
	this.shape_3.setTransform(191,10.9);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FF9900").s().p("AgvAAIBfhkIAADJg");
	this.shape_4.setTransform(93.7,9.7);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("Ah7C9IAAl5ID3AAIAAF5g");
	this.shape_5.setTransform(94.1,9.7);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FF9900").s().p("AhHBYQgfgfAAgqQAAgjAXgdIgUgWQgDgDAAgGQAAgFADgFQADgFAGgBIBkgVQAGgBAFACQAFADACAFQACAFgCAFIgcBjQgCAFgEADQgFADgGAAQgFgBgEgEIgWgWQgKAOAAAQQAAAZASARQARASAXAAQAYAAARgSIABAAQARgRAAgZQAAgPgHgMQgLgQABgMQAFgTATACQALAEAMASQAOAXAAAbIAAACQAAAqgeAdQgeAfgrAAQgpAAgegfg");
	this.shape_6.setTransform(104.1,6.8);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("AhZBrQgngnAAg1QAAghARgcIgGgHQgLgKAAgQQgBgOAJgMIAAgBQAJgMAPgDIABAAIBkgVIABAAQANgDAMAGIADABQAMAHAFAMIABABQAFANgEAOIAAABIgDAJQAIgCALABIAGABQARAFASAZIABACQASAdAAAjIAAACQgBA1glAlQgmAlg1AAQg0AAglglgAgWAnIAAAAQAKAKAMAAQANAAALgKIACgCQAIgJAAgNQAAgJgEgGIgDgEIgFAMQgEAOgLAIIgBAAQgKAJgOgCIgHgBIADADg");
	this.shape_7.setTransform(104.1,6.8);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("rgba(0,0,0,0.2)").s().p("AhiB0QgqgqAAg7QAAgfAOgcQgOgOgBgUQgBgTAMgPIABgBQALgPAQgFIAFgBIBkgVIACAAQARgDAPAHIABABIACABQAQAIAHARIABABQAFAOgCAOIADAAIAKACQAUAFAVAeIABACIABAAIAAABQATAgAAAmIAAACIAAAAQgBA6goApQgqApg7AAQg5AAgpgpg");
	this.shape_8.setTransform(104,6.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("rgba(0,0,0,0.2)").s().p("AicAQQgSgGAhgIQATgDAegEQgGgDALgCQAKgDAUgCIACAAIAmgEIAFAAIBxgDIACAAIAeABIACAAQALACgDACQgCACgKACIADAAIAAAAIAIAAQARABAEAFIAAAAQABAEgWAFIgCAAIAAAAQgjAJg/AFQg/AHg7gBQg7ABgRgHg");
	this.shape_9.setTransform(108.1,20.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#000000").s().p("A8GBNQgNgHgJgNQgIgNAAgRQAAgQAIgLQAIgOAOgHQANgIASAAQANAAALAEQAMAGAJAJQAJAKAFAMIgjAAQgEgIgGgEQgGgBgIAAQgNAAgIAHQgIAHAAAOQAAAIADAHQAEAHAHAEQAHAEAIAAQAIAAAFgDQAGgDAFgIIAjAAQgIAVgPALQgPAKgUAAQgSAAgOgIgA+OBOQgOgIgIgNQgIgNAAgRQAAgQAIgLQAIgNAOgIQANgIASAAQARAAANAIQAOAIAHANQAIAMAAAQIAAAGIgBAHIhVAAQADAHAHAEQAHAFALAAIAHAAIAHgCIAJgDIAhAAQgEAOgJAGQgJAIgLACQgLADgMAAQgSAAgOgHgA9RASQgDgKgHgHQgIgDgLAAQgLAAgHADQgIAGgDALIA6AAIAAAAgA/iBVIAAioIAgAAIAACogEghTABOQgOgIgIgNQgJgNAAgRQAAgQAIgLQAIgNAOgIQAOgIARAAQARAAAOAIQANAIAIANQAHAMABAQIgBAGIgBAHIhUAAQADAHAHAEQAHAFAKAAIAIAAIAGgCIAJgDIAiAAQgFAOgJAGQgIAIgMACQgLADgLAAQgSAAgOgHgEggWAASQgDgKgIgHQgHgDgMAAQgKAAgIADQgHAGgEALIA7AAIAAAAgEgjWABPQgMgHgIgMQgIgMgCgQIAkAAQABAKAGAEQAFAGAKAAQAJgBAFgFQAFgEAAgIQAAgDgDgDIgIgGIgHgFIgDgCIgDgBIgBAAIgDgCIgLgGQgKgGgHgDQgHgGgEgJQgDgHAAgLQAAgNAHgLQAGgLAMgGQALgGAOAAQAPAAALAFQALAHAHAKQAHAMABAQIgjAAQgBgJgFgEQgEgEgHAAQgGAAgEADQgEACgCADQgCADAAADIABAFIADAFIAJAHIARAJQAVAKALAIQAMAMAAAMQAAAPgHAMQgHAMgNAHQgMAHgQAAQgQAAgMgGgA51BUIgKgEQgFgCgEgGQgDgGAAgKIAAg4IgXAAIAAgdIAXAAIAAg2IAfAAIAAA2IAWAAIAAAdIgWAAIAAA0QAAAEADABQADABADAAIAIgDQADgBACgCIAAAYIgEADIgFADQgEACgEAAIgFABIgJgBgEAjSABUIAAggIAjAAIAAAggEAhyABQQgLgFgHgIQgHgJgCgPIAiAAQACAHAGADQAFADAGAAQAGAAADgCQAEgDAAgDQgBgDgDgDIgJgDIgJgDQgUgFgJgIQgKgHAAgNQAAgIAHgIQAGgIAKgFQALgEANAAQAMAAALAEQAKAEAGAJQAHAHABALIghAAQgBgFgDAAQgEgDgHAAQgFAAgDADQgEAAAAADQAAAAAAABQAAAAAAABQAAAAABABQAAABABAAIAHADIAPAFQAOAFAIAEQAIAEAEAFQAEAFABAHQACALgHAJQgHAJgMAFQgMAFgOAAQgOAAgLgEgEAgiABUIAAioIAfAAIAACogAfpBUIAAgNQgIAHgIADQgIADgLAAQgRAAgNgHQgNgIgHgNQgIgNAAgRQAAgRAIgLQAHgNANgHQAOgIARAAQAKAAAJADQAIADAHAGIAAgKIAdAAIAABwgAe0AFQgIAIAAAOQAAANAIAIQAIAIAOAAQAJAAAHgEQAHgEADgGQAEgHAAgJQAAgIgEgHQgEgHgHgEQgHgCgIAAQgOAAgIAHgAdZBUIAAg+QAAgLgDgFQgCgGgEAAQgEgCgGABQgGgBgFACQgEACgCAGQgDAIAAAMIAAA4IgfAAIAAg+QAAgLgCgFQgDgGgEAAQgEgCgGABQgHgBgEACQgEACgDAGQgCAIAAAMIAAA4IgfAAIAAhyIAdAAIAAAJQAFgFAHgCQAGgCAJAAQALAAAIADQAIAEAGAIQAGgIAJgEQAJgDALAAQAXAAAMAMQAMANAAAYIAABBgAaTBUIAAhyIAfAAIAABygAYkBMQgOgHgIgOQgIgNAAgQQAAgRAIgKQAIgOANgHQAOgIARAAQANAAAMAEQALAGAJAJQAJAJAFAMIgiAAQgFgHgGgDQgFgCgJAAQgNAAgIAHQgIAHAAAOQAAAIAEAIQAEAGAGAEQAHAEAJAAQAHAAAGgDQAGgEAFgHIAiAAQgIAVgPAKQgPALgUAAQgRAAgOgIgAWcBNQgOgIgIgNQgJgNAAgRQAAgQAIgLQAIgNAOgIQAOgIARAAQARAAAOAIQANAIAIANQAHALABARIgBAGIgBAHIhUAAQADAHAHAFQAHAEAKAAIAIAAIAGgCIAJgCIAiAAQgFANgJAGQgIAIgMACQgLADgLAAQgSAAgOgHgAXZARQgDgKgIgHQgHgDgMAAQgKAAgIADQgHAGgEALIA7AAIAAAAgAVLBUIAAgNQgIAHgIADQgIADgLAAQgQAAgNgHQgNgIgIgNQgHgNAAgRQAAgQAHgLQAIgNANgIQANgIAQAAQAKAAAIACQAIADAGAFIAAhAIAgAAIAACogAUdAAQgHAEgEAGQgEAHAAAIQAAAJAEAHQAEAHAHAEQAHAEAJABQAIgBAHgEQAGgEAEgGQAEgHAAgJQAAgIgEgIQgEgGgGgEQgHgCgJAAQgIAAgHACgARMBMQgNgHgJgOQgIgNAAgQQAAgQAIgLQAIgNAOgIQAOgIARAAQARAAAOAIQAOAIAIANQAIALAAARQAAAPgIANQgIAOgOAHQgOAIgRAAQgRAAgOgIgARcAAQgGAEgEAGQgEAIgBAHQABAKAEAGQAEAHAGAEQAHAEAIAAQAIAAAHgEQAHgEAEgHQAEgHAAgIQAAgJgEgGQgEgHgHgEQgHgCgIAAQgIAAgHACgAPmBUIgThCIgUBCIgUAAIgphyIAiAAIASA7IARg7IAZAAIAQA7IASg7IAiAAIgqBygAKaBUIAAhyIAdAAIAAAJQAEgGAFgBQAFgCAIAAIACAAIAGABIAHABIAEACIAAAbIgJgBIgIAAQgLAAgGAEQgFAFAAAMIAAA/gAIqBNQgOgIgIgNQgIgNAAgRQAAgQAIgLQAIgNAOgIQANgIASAAQARAAANAIQAOAIAHANQAIALAAARIAAAGIgBAHIhVAAQADAHAHAFQAHAEALAAIAHAAIAHgCIAJgCIAhAAQgEANgJAGQgJAIgLACQgLADgMAAQgSAAgOgHgAJnARQgDgKgHgHQgIgDgLAAQgLAAgHADQgIAGgDALIA6AAIAAAAgAHZBUIAAg4QAAgLgCgHQgCgGgEgDQgEgBgHAAQgHAAgEABQgFADgDAGQgCAHAAALIAAA4IgfAAIAAioIAfAAIAABAQAFgEAHgCQAGgCAIAAQAVAAAMAMQAMANAAAZIAAA+gADFBMQgOgHgIgOQgIgNgBgQQABgQAIgLQAIgNAOgIQANgIARAAQASAAAOAIQAOAIAIANQAIALAAARQAAAPgJANQgIAOgOAHQgNAIgRAAQgRAAgOgIgADVAAQgHAEgEAGQgEAIAAAHQAAAKAEAGQAEAHAHAEQAGAEAJAAQAIAAAHgEQAGgEAEgHQAEgHAAgIQAAgJgEgGQgEgHgGgEQgHgCgIAAQgJAAgGACgAB1BUIAAg4QAAgNgDgIQgCgGgEgBQgEgCgGABQgGAAgEABQgFABgDAFQgCADgBAFIgBARIAAA1IgfAAIAAhyIAdAAIAAAKQAHgFAHgDQAHgCAIAAQAMAAAJAEQAKAEAGAJIAFAJQACAEAAAHQABAHAAAJIAAA9gAgIBUIAAgNQgHAHgIADQgJADgKAAQgRAAgNgHQgOgIgHgNQgHgNAAgRQAAgRAHgLQAIgNANgHQANgIARAAQALAAAIADQAIADAHAGIAAgKIAbAAIAABwgAg9AFQgIAIAAAOQAAANAIAIQAJAIANAAQAKAAAGgEQAHgEAEgGQADgHAAgJQAAgIgEgHQgEgHgGgEQgHgCgJAAQgNAAgJAHgAjPBUIAAgNQgIAHgIADQgIADgLAAQgQAAgNgHQgNgIgIgNQgHgNAAgRQAAgQAHgLQAIgNANgIQANgIAQAAQAKAAAIACQAIADAGAFIAAhAIAgAAIAACogAj9AAQgHAEgEAGQgEAHAAAIQAAAJAEAHQAEAHAHAEQAHAEAJABQAIgBAHgEQAGgEAEgGQAEgHAAgJQAAgIgEgIQgEgGgGgEQgHgCgJAAQgIAAgHACgAleBUIAAgNQgIAHgIADQgIADgLAAQgQAAgNgHQgNgIgIgNQgHgNAAgRQAAgQAHgLQAIgNANgIQANgIAQAAQAKAAAIACQAIADAGAFIAAhAIAgAAIAACogAmMAAQgHAEgEAGQgEAHAAAIQAAAJAEAHQAEAHAHAEQAHAEAJABQAIgBAHgEQAGgEAEgGQAEgHAAgJQAAgIgEgIQgEgGgGgEQgHgCgJAAQgIAAgHACgAnuBUIAAgNQgHAHgIADQgJADgKAAQgRAAgNgHQgOgIgHgNQgHgNAAgRQAAgRAHgLQAIgNANgHQANgIARAAQALAAAIADQAIADAHAGIAAgKIAdAAIAABwgAojAFQgIAIAAAOQAAANAIAIQAJAIANAAQAKAAAGgEQAHgEAEgGQADgHAAgJQAAgIgEgHQgEgHgGgEQgHgCgJAAQgNAAgJAHgArtBMQgNgHgJgOQgIgNAAgQQAAgQAIgLQAIgNAOgIQAOgIARAAQARAAAOAIQAOAIAIANQAIALAAARQAAAPgIANQgIAOgOAHQgOAIgRAAQgRAAgOgIgArdAAQgGAEgEAGQgEAIgBAHQABAKAEAGQAEAHAGAEQAHAEAIAAQAIAAAHgEQAHgEAEgHQAEgHAAgIQAAgJgEgGQgEgHgHgEQgHgCgIAAQgIAAgHACgANSBTIgKgEQgFgCgDgGQgEgGAAgKIAAg3IgXAAIAAgeIAXAAIAAg2IAgAAIAAA2IAWAAIAAAeIgXAAIAAA0QABADACABQADABAEAAIAHgDQAEgBABgCIAAAYIgDADIgGADQgDACgFAAIgFABIgJgBgAFYBTIgKgEQgFgCgEgGQgDgGAAgKIAAg3IgXAAIAAgeIAXAAIAAg2IAfAAIAAA2IAWAAIAAAeIgWAAIAAA0QAAADADABQADABADAAIAIgDQADgBACgCIAAAYIgEADIgFADQgEACgEAAIgFABIgJgBgAs9BTIgKgEQgFgCgDgGQgEgGAAgKIAAg3IgXAAIAAgeIAXAAIAAg2IAgAAIAAA2IAWAAIAAAeIgXAAIAAA0QABADACABQADABAEAAIAHgDQAEgBABgCIAAAYIgDADIgGADQgDACgFAAIgFABIgJgBgAvXgWIAHgMIAEgIIABgFIABgFIgOAAIAAgeIAjAAIAAAbIgEALIgEAJIgFAHIgEAGgAwGgWIAHgMIAEgIIACgFIABgFIgOAAIAAgeIAjAAIAAAbIgFALIgEAJIgEAHIgEAGgA3SgWIAAgbIAFgNIAEgJIAEgFIAFgGIARAAIgHALIgEAIIgCAGIgBAEIAOAAIAAAfgA4AgWIAAgbIAFgNIAEgJIAEgFIAFgGIARAAIgHALIgEAIIgCAGIgBAEIAOAAIAAAfgAaTg2IAAgeIAgAAIAAAeg");
	this.shape_10.setTransform(227.9,7.9);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).to({state:[{t:this.shape_2},{t:this.instance},{t:this.shape_1}]},1).to({state:[{t:this.shape_5},{t:this.shape_4},{t:this.shape_3}]},1).to({state:[{t:this.shape_10},{t:this.shape_9},{t:this.shape_8},{t:this.shape_7},{t:this.shape_6}]},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0.1,-0.1,439.2,23);


(lib.cbModel_Tenths1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// highlight
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#99FFFF").s().p("AggAhQgOgOAAgTQAAgSAOgOQAOgOASAAQATAAAOAOQAOAOAAASQAAATgOAOQgOAOgTAAQgSAAgOgOgAANgLIgBAAIgCABIAAADIAEAAIAAAUIAEAAIAAgaIgEAAIgBACgAACANIADAAIAAgDIgDAAgAgPgMIgEAEIAAAFIAAAGIABAGIADADIAFABQAEABACgDQACgCAAgGIAAgGIgBgFQAAgBAAAAQAAgBgBAAQAAgBgBAAQAAAAAAgBIgGgBIgEABgAgKAKQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAIgCgDIgBgEIAAgFIABgEIACgDIACgBIAEABIACADIAAAEIAAAFIAAAEIgCADIgCAAIgBAAg");
	this.shape.setTransform(5,5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#000000").s().p("AAPANIAAgUIgEAAIAAgDIACgBIABAAIACgCIADAAIAAAagAADANIAAgDIADAAIAAADgAgOAMIgDgDIgBgGIAAgGIABgFIADgEIAFgBIAFABQAAABABAAQAAAAABABQAAAAAAABQAAAAABABIABAFIAAAGQAAAGgCACQgDADgEgBIgFgBgAgGAKIACgDIAAgEIAAgFIAAgEIgCgDIgDgBIgDABIgCADIgBAEIAAAFIABAEIACADQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAIADAAg");
	this.shape_1.setTransform(4.9,5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1},{t:this.shape}]},1).wait(1));

	// cube
	this.instance = new lib.numdotlvl_yellow("single",0);
	this.instance.setTransform(5,5,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// hit
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(255,255,255,0)").s().p("AgxAxIAAhiIBiAAIAABig");
	this.shape_2.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10,10);


(lib.cbModel_Tenths = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// highlight
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAPANIAAgUIgEAAIAAgDIACgBIABAAIACgCIADAAIAAAagAADANIAAgDIADAAIAAADgAgOAMIgDgDIgBgGIAAgGIABgFIADgEIAFgBIAFABQAAABABAAQAAAAABABQAAAAAAABQAAAAABABIABAFIAAAGQAAAGgCACQgDADgEgBIgFgBgAgGAKIACgDIAAgEIAAgFIAAgEIgCgDIgDgBIgDABIgCADIgBAEIAAAFIABAEIACADQAAAAABAAQAAAAABAAQAAAAAAAAQABAAAAAAIADAAg");
	this.shape.setTransform(4.9,5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#99FFFF").s().p("AggAhQgOgOAAgTQAAgSAOgOQAOgOASAAQATAAAOAOQAOAOAAASQAAATgOAOQgOAOgTAAQgSAAgOgOgAANgLIgBAAIgCABIAAADIAEAAIAAAUIAEAAIAAgaIgEAAIgBACgAACANIADAAIAAgDIgDAAgAgPgMIgEAEIAAAFIAAAGIABAGIADADIAFABQAEABACgDQACgCAAgGIAAgGIgBgFQAAgBAAAAQAAgBgBAAQAAgBgBAAQAAAAAAgBIgGgBIgEABgAgKAKQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAIgCgDIgBgEIAAgFIABgEIACgDIACgBIAEABIACADIAAAEIAAAFIAAAEIgCADIgCAAIgBAAg");
	this.shape_1.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1},{t:this.shape}]},1).wait(1));

	// cube
	this.instance = new lib.numdotlvl_darkblue("single",0);
	this.instance.setTransform(5,5,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// hit
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(255,255,255,0)").s().p("AgxAxIAAhiIBiAAIAABig");
	this.shape_2.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10,10);


(lib.cbModel_Tens1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// highlight
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AABAMIgBgDIAAgGIAAgGIAAgFIABgEIAFgBIAFABQABABAAAAQAAAAABABQAAAAAAABQABAAAAABIABAFIAAAGQAAAGgCACQgCADgEgBIgGgBgAAJAKIACgDIAAgEIAAgFIAAgEIgCgDIgDgBIgDABIgCADIgBAEIAAAFIABAEIACADQABAAAAAAQAAAAABAAQAAAAABAAQAAAAABAAIACAAgAgKANIAAgUIgEAAIAAgDIACgBIABAAIACgCIACAAIAAAag");
	this.shape.setTransform(5,5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#99FFFF").s().p("AggAhQgOgOAAgTQAAgSAOgOQAOgOASAAQATAAAOAOQAOAOAAASQAAATgOAOQgOAOgTAAQgSAAgOgOg");
	this.shape_1.setTransform(5,5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#99FFFF").s().p("AgfAfQgMgNAAgSQAAgRAMgOQAOgMARAAQASAAANAMQAOAOAAARQAAASgOANQgNAOgSAAQgRAAgOgOg");
	this.shape_2.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(1));

	// cube
	this.instance = new lib.numdotlvl_purple("single",0);
	this.instance.setTransform(5,5,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// hit
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(255,255,255,0)").s().p("AgxAxIAAhiIBiAAIAABig");
	this.shape_3.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10,10);


(lib.cbModel_Tens = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// highlight
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AABAMIgBgDIAAgGIAAgGIAAgFIABgEIAFgBIAFABQABABAAAAQAAAAABABQAAAAAAABQABAAAAABIABAFIAAAGQAAAGgCACQgCADgEgBIgGgBgAAJAKIACgDIAAgEIAAgFIAAgEIgCgDIgDgBIgDABIgCADIgBAEIAAAFIABAEIACADQABAAAAAAQAAAAABAAQAAAAABAAQAAAAABAAIACAAgAgKANIAAgUIgEAAIAAgDIACgBIABAAIACgCIACAAIAAAag");
	this.shape.setTransform(5,5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#99FFFF").s().p("AggAhQgOgOAAgTQAAgSAOgOQAOgOASAAQATAAAOAOQAOAOAAASQAAATgOAOQgOAOgTAAQgSAAgOgOgAABgMIgCAEIAAAFIAAAGIABAGIABADIAFABQAEABACgDQACgCAAgGIAAgGIgBgFQAAgBAAAAQAAgBgBAAQAAgBgBAAQAAAAAAgBIgGgBIgEABgAgMgLIgBAAIgBABIAAADIADAAIAAAUIAEAAIAAgaIgDAAIgCACgAAGAKQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAIgCgDIgBgEIAAgFIABgEIACgDIACgBIAEABIACADIAAAEIAAAFIAAAEIgCADIgCAAIgBAAg");
	this.shape_1.setTransform(5,5);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#99FFFF").s().p("AgfAfQgMgNAAgSQAAgRAMgOQAOgMARAAQASAAANAMQAOAOAAARQAAASgOANQgNAOgSAAQgRAAgOgOg");
	this.shape_2.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_2},{t:this.shape_1},{t:this.shape}]},1).wait(1));

	// cube
	this.instance = new lib.numdotlvl_purple("single",0);
	this.instance.setTransform(5,5,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// hit
	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("rgba(255,255,255,0)").s().p("AgxAxIAAhiIBiAAIAABig");
	this.shape_3.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get(this.shape_3).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10,10);


(lib.cbModel_Ones1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// highlight
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAAANIAAgUIgCAAIAAgDIACgBIAAAAIAAgCIADAAIAAAag");
	this.shape.setTransform(4.9,5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#99FFFF").s().p("AggAhQgOgNAAgUQAAgSAOgOQAOgOASAAQAUAAANAOQAOAOAAASQAAAUgOANQgNAOgUAAQgSAAgOgOgAgBgLIgBAAIgCABIAAADIAEAAIAAAUIACAAIAAgaIgCAAIgBACg");
	this.shape_1.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1},{t:this.shape}]},1).wait(1));

	// cube
	this.instance = new lib.numdotlvl_pink("single",0);
	this.instance.setTransform(5,5,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// hit
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(255,255,255,0)").s().p("AgxAxIAAhiIBiAAIAABig");
	this.shape_2.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10,10);


(lib.cbModel_Ones = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// highlight
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAAANIAAgUIgCAAIAAgDIACgBIAAAAIAAgCIADAAIAAAag");
	this.shape.setTransform(4.9,5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#99FFFF").s().p("AggAhQgOgNAAgUQAAgSAOgOQAOgOASAAQAUAAANAOQAOAOAAASQAAAUgOANQgNAOgUAAQgSAAgOgOg");
	this.shape_1.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1},{t:this.shape}]},1).wait(1));

	// cube
	this.instance = new lib.numdotlvl_pink("single",0);
	this.instance.setTransform(5,5,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// hit
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(255,255,255,0)").s().p("AgxAxIAAhiIBiAAIAABig");
	this.shape_2.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10,10);


(lib.cbModel_Hundredths1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// highlight
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAZANIAAgUIgFAAIAAgDIACgBIABAAIACgCIADAAIAAAagAADAMIgDgDIAAgGIAAgGIAAgFQAAgBAAAAQAAgBABAAQAAgBABAAQAAAAABgBIAEgBIAFABQABABAAAAQAAAAABABQAAAAAAABQABAAAAABIABAFIAAAGQAAAGgCACQgCADgEgBIgFgBgAALAKIABgDIABgEIAAgFIgBgEIgBgDIgEgBIgDABIgBADIgBAEIAAAFIABAEQAAABAAAAQAAAAAAABQAAAAABAAQAAAAAAABQABAAAAAAQAAAAABAAQAAAAABAAQAAAAABAAIADAAgAgGANIAAgFIAEAAIAAAFgAgWAMQgBAAgBAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQgCgCAAgEIAAgGIABgFQAAgBABAAQAAgBAAAAQABgBAAAAQABAAABgBIAEgBIAEABQABABAAAAQABAAAAABQABAAAAABQAAAAAAABQACACAAADIAAAGQAAAGgDACQgCADgEgBIgEgBgAgPAKQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAAAgBIAAgEIAAgFIAAgEIgCgDIgDgBIgDABIgCADIgBAEIAAAFIABAEQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAABIADAAIADAAg");
	this.shape.setTransform(5.1,5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#99FFFF").s().p("AggAhQgOgNAAgUQAAgSAOgOQAOgOASAAQAUAAANAOQAOAOAAASQAAAUgOANQgNAOgUAAQgSAAgOgOg");
	this.shape_1.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1},{t:this.shape}]},1).wait(1));

	// cube
	this.instance = new lib.numdotlvl_red("single",0);
	this.instance.setTransform(5,5,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// hit
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(255,255,255,0)").s().p("AgxAxIAAhiIBiAAIAABig");
	this.shape_2.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10,10);


(lib.cbModel_Hundredths = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// highlight
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AAaANIAAgUIgEAAIAAgDIACgBIABAAIACgCIADAAIAAAagAAFAMQgBAAgBAAQAAgBAAAAQgBgBAAAAQAAgBAAAAQgCgCAAgEIAAgGIABgFQAAgBABAAQAAgBAAAAQABgBAAAAQABAAABgBIAEgBIAEABQABABAAAAQABAAAAABQABAAAAABQAAAAAAABQACACAAADIAAAGQAAAGgDACQgCADgEgBIgEgBgAAMAKQAAgBABAAQAAAAAAAAQABgBAAAAQAAAAAAgBIAAgEIAAgFIAAgEIgCgDIgDgBIgDABIgCADIgBAEIAAAFIABAEQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAABIADAAIADAAgAgGANIAAgDIADAAIAAADgAgZAMIgDgDIgBgGIAAgGIABgFQAAgBABAAQAAgBAAAAQABgBAAAAQABAAAAgBIAFgBIAFABQAAABAAAAQABAAAAABQABAAAAABQAAAAABABIAAAFIAAAGQABAGgCACQgDADgEgBIgFgBgAgRAKIACgDIABgEIAAgFIgBgEIgCgDIgDgBIgDABIgCADIgBAEIAAAFIABAEQAAABAAAAQAAAAABABQAAAAAAAAQABAAAAABQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAIADAAg");
	this.shape.setTransform(4.9,5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#99FFFF").s().p("AggAhQgOgOAAgTQAAgSAOgOQAOgOASAAQATAAAOAOQAOAOAAASQAAATgOAOQgOAOgTAAQgSAAgOgOgAAYgLIgBAAIgCABIAAADIAEAAIAAAUIAEAAIAAgaIgDAAIgCACgAAEgMQgBABgBAAQAAAAgBABQAAAAAAABQgBAAAAABIAAAFIAAAGQAAAEABACQAAAAAAABQAAAAABABQAAAAAAABQABAAABAAIAEABQAEABACgDQADgCAAgGIAAgGQAAgDgCgCQAAgBAAAAQAAgBgBAAQAAgBgBAAQAAAAgBgBIgEgBIgEABgAgHANIADAAIAAgDIgDAAgAgagMQAAABgBAAQAAAAgBABQAAAAAAABQgBAAAAABIgBAFIAAAGIABAGIADADIAFABQAEABADgDQACgCgBgGIAAgGIAAgFQgBgBAAAAQAAgBgBAAQAAgBgBAAQAAAAAAgBIgFgBIgFABgAAIAKIgDAAQAAgBgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIgBgEIAAgFIABgEIACgDIADgBIADABIACADIAAAEIAAAFIAAAEQAAABAAAAQAAAAgBABQAAAAAAAAQgBAAAAABIgCAAIgBAAgAgVAKQAAAAgBAAQAAAAgBAAQAAAAAAAAQgBAAAAAAQAAgBgBAAQAAAAAAAAQgBgBAAAAQAAAAAAgBIgBgEIAAgFIABgEIACgDIADgBIADABIACADIABAEIAAAFIgBAEIgCADIgCAAIgBAAg");
	this.shape_1.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1},{t:this.shape}]},1).wait(1));

	// cube
	this.instance = new lib.numdotlvl_red("single",0);
	this.instance.setTransform(5,5,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// hit
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(255,255,255,0)").s().p("AgxAxIAAhiIBiAAIAABig");
	this.shape_2.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10,10);


(lib.cbModel_Hundreds1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// highlight
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AANAMQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAAAQgCgCAAgEIAAgGIABgFQAAgBABAAQAAgBABAAQAAgBABAAQAAAAABgBIAEgBIAFABQAAABABAAQAAAAAAABQABAAAAABQAAAAABABQABACAAADIAAAGQAAAGgCACQgCADgFgBIgEgBgAAUAKQABgBAAAAQAAAAABAAQAAgBAAAAQAAAAAAgBIABgEIAAgFIgBgEIgCgDIgDgBIgDABIgCADIgBAEIAAAFIABAEQAAABABAAQAAAAAAABQAAAAABAAQAAAAAAABIADAAIADAAgAgIAMIgDgDIgBgGIAAgGIABgFQABgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBIAFgBIADABQAAABABAAQAAAAABABQAAAAAAABQABAAAAABIABAFIAAAGQAAAGgCACQgCADgDgBIgFgBgAAAAKIAAgDIABgEIAAgFIgBgEIAAgDIgDgBIgDABIgCADIgBAEIAAAFIABAEQAAABABAAQAAAAAAABQAAAAABAAQAAAAAAABQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAIADAAgAgVANIAAgUIgEAAIAAgDIACgBIABAAIABgCIADAAIAAAag");
	this.shape.setTransform(5,5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#99FFFF").s().p("AggAhQgOgNAAgUQAAgSAOgOQAOgOASAAQAUAAANAOQAOAOAAASQAAAUgOANQgNAOgUAAQgSAAgOgOg");
	this.shape_1.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1},{t:this.shape}]},1).wait(1));

	// cube
	this.instance = new lib.numdotlvl_blue("single",0);
	this.instance.setTransform(5,5,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// hit
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(255,255,255,0)").s().p("AgxAxIAAhiIBiAAIAABig");
	this.shape_2.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10,10);


(lib.cbModel_Hundreds = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// highlight
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#000000").s().p("AANAMQgBAAAAAAQgBgBAAAAQgBgBAAAAQAAgBAAAAQgCgCAAgEIAAgGIABgFQAAgBABAAQAAgBABAAQAAgBABAAQAAAAABgBIAEgBIAFABQAAABABAAQAAAAAAABQABAAAAABQAAAAABABQABACAAADIAAAGQAAAGgCACQgCADgFgBIgEgBgAAUAKQABgBAAAAQAAAAABAAQAAgBAAAAQAAAAAAgBIABgEIAAgFIgBgEIgCgDIgDgBIgDABIgCADIgBAEIAAAFIABAEQAAABABAAQAAAAAAABQAAAAABAAQAAAAAAABIADAAIADAAgAgIAMIgDgDIgBgGIAAgGIABgFQABgBAAAAQAAgBABAAQAAgBAAAAQABAAAAgBIAFgBIADABQAAABABAAQAAAAABABQAAAAAAABQABAAAAABIABAFIAAAGQAAAGgCACQgCADgDgBIgFgBgAAAAKIAAgDIABgEIAAgFIgBgEIAAgDIgDgBIgDABIgCADIgBAEIAAAFIABAEQAAABABAAQAAAAAAABQAAAAABAAQAAAAAAABQAAAAABAAQAAAAAAAAQABAAAAAAQABAAAAAAIADAAgAgVANIAAgUIgEAAIAAgDIACgBIABAAIABgCIADAAIAAAag");
	this.shape.setTransform(5,5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#99FFFF").s().p("AggAhQgOgNAAgUQAAgSAOgOQAOgOASAAQAUAAANAOQAOAOAAASQAAAUgOANQgNAOgUAAQgSAAgOgOg");
	this.shape_1.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[]}).to({state:[{t:this.shape_1},{t:this.shape}]},1).wait(1));

	// cube
	this.instance = new lib.numdotlvl_blue("single",0);
	this.instance.setTransform(5,5,0.75,0.75);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(2));

	// hit
	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("rgba(255,255,255,0)").s().p("AgxAxIAAhiIBiAAIAABig");
	this.shape_2.setTransform(5,5);

	this.timeline.addTween(cjs.Tween.get(this.shape_2).wait(2));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10,10);


(lib.mc_cbModel_Tenths1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.cbModel_Tens = new lib.cbModel_Tenths1();
	this.cbModel_Tens.setTransform(0,0,4,4);

	this.timeline.addTween(cjs.Tween.get(this.cbModel_Tens).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,40,40);


(lib.mc_cbModel_Tenths = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.cbModel_Tenths = new lib.cbModel_Tenths();
	this.cbModel_Tenths.setTransform(14,8.3,1,1,0,0,0,14,8.3);

	this.timeline.addTween(cjs.Tween.get(this.cbModel_Tenths).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10,10);


(lib.mc_cbModel_Tens1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.cbModel_Tens = new lib.cbModel_Tens1();
	this.cbModel_Tens.setTransform(0,0,4,4);

	this.timeline.addTween(cjs.Tween.get(this.cbModel_Tens).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,40,40);


(lib.mc_cbModel_Tens = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.cbModel_Tens = new lib.cbModel_Tens();
	this.cbModel_Tens.setTransform(14,8.3,1,1,0,0,0,14,8.3);

	this.timeline.addTween(cjs.Tween.get(this.cbModel_Tens).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,10,10);


(lib.mc_cbModel_Ones1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.hsModel_One = new lib.cbModel_Ones1();
	this.hsModel_One.setTransform(20,20,4,4,0,0,0,5,5);

	this.timeline.addTween(cjs.Tween.get(this.hsModel_One).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,40,40);


(lib.mc_cbModel_Ones = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.cbModel_Ones = new lib.cbModel_Ones();
	this.cbModel_Ones.setTransform(14.4,16,4,4,0,0,0,3.6,4);

	this.timeline.addTween(cjs.Tween.get(this.cbModel_Ones).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,40,40);


(lib.mc_cbModel_Hundredths1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.hsModel_Hundred = new lib.cbModel_Hundredths1();
	this.hsModel_Hundred.setTransform(20,20,4,4,0,0,0,5,5);

	this.timeline.addTween(cjs.Tween.get(this.hsModel_Hundred).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,40,40);


(lib.mc_cbModel_Hundredths = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.hsModel_Hundred = new lib.cbModel_Hundredths();
	this.hsModel_Hundred.setTransform(20,20,4,4,0,0,0,5,5);

	this.timeline.addTween(cjs.Tween.get(this.hsModel_Hundred).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,40,40);


(lib.mc_cbModel_Hundreds1 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.hsModel_Hundred = new lib.cbModel_Hundreds1();
	this.hsModel_Hundred.setTransform(20,20,4,4,0,0,0,5,5);

	this.timeline.addTween(cjs.Tween.get(this.hsModel_Hundred).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,40,40);


(lib.mc_cbModel_Hundreds = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// Layer 1
	this.hsModel_Hundred = new lib.cbModel_Hundreds();
	this.hsModel_Hundred.setTransform(20,20,4,4,0,0,0,5,5);

	this.timeline.addTween(cjs.Tween.get(this.hsModel_Hundred).to({_off:true},1).wait(1));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,40,40);


(lib.mcClone = function() {
	this.initialize();

	// Layer 1
	this.mc_cbModel_Hundreds1 = new lib.mc_cbModel_Hundreds1();
	this.mc_cbModel_Hundreds1.setTransform(169.9,0,1,0.999);

	this.mc_cbModel_Hundreds = new lib.mc_cbModel_Hundreds();
	this.mc_cbModel_Hundreds.setTransform(169.9,48,1,0.999);

	this.mc_cbModel_Hundreds1_1 = new lib.mc_cbModel_Hundredths1();
	this.mc_cbModel_Hundreds1_1.setTransform(126.9,0,1,0.999);

	this.mc_cbModel_Hundreds_1 = new lib.mc_cbModel_Hundredths();
	this.mc_cbModel_Hundreds_1.setTransform(126.9,48,1,0.999);

	this.mc_cbModel_Tens1 = new lib.mc_cbModel_Tens1();
	this.mc_cbModel_Tens1.setTransform(0,0,1,0.999);

	this.mc_cbModel_Tens = new lib.mc_cbModel_Tens();
	this.mc_cbModel_Tens.setTransform(0,48,4,3.997);

	this.mc_cbModel_Ones = new lib.mc_cbModel_Ones();
	this.mc_cbModel_Ones.setTransform(84.6,48);

	this.mc_cbModel_Ones1 = new lib.mc_cbModel_Ones1();
	this.mc_cbModel_Ones1.setTransform(42.3,48);

	this.mc_cbModel_Tenths = new lib.mc_cbModel_Tenths();
	this.mc_cbModel_Tenths.setTransform(42.3,0,4,4);

	this.mc_cbModel_Tenths1 = new lib.mc_cbModel_Tenths1();
	this.mc_cbModel_Tenths1.setTransform(84.6,0);

	this.addChild(this.mc_cbModel_Tenths1,this.mc_cbModel_Tenths,this.mc_cbModel_Ones1,this.mc_cbModel_Ones,this.mc_cbModel_Tens,this.mc_cbModel_Tens1,this.mc_cbModel_Hundreds_1,this.mc_cbModel_Hundreds1_1,this.mc_cbModel_Hundreds,this.mc_cbModel_Hundreds1);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,209.9,88);


// stage content:



(lib.placevaluechip_add1_10_canvas = function() {
	this.initialize();

	// Instruction
	this.mcInstruction = new lib.mcInstruction();
	this.mcInstruction.setTransform(250.6,60.5,1,1,0,0,0,217.6,11.5);

	// Tool
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgPBlQgGgGAAgLIAAiVIggAAQgMAAgEgGQgFgHAAgIQAAgIAFgGQAFgGALAAIBrAAQAKAAAGAGQAFAGAAAIQAAAIgEAHQgGAGgLAAIggAAIAACVQAAALgGAGQgHAGgJAAQgIAAgHgGg");
	this.shape.setTransform(801.4,210.1);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Ag0BfQgXgOgNgZQgNgZgBgfQABgeANgZQAMgZAYgOQAXgPAdAAQAeAAAXAPQAXAPANAZQANAZABAdQAAAfgNAZQgNAZgXAOQgXAPgfAAQgdAAgXgPgAgeg6QgMAKgHAPQgGAQAAARQAAASAGAQQAGAPANAKQAMAJASAAQATAAAMgJQANgKAGgPQAGgQAAgSQAAgRgGgQQgHgPgMgKQgNgJgSgBQgRABgNAJg");
	this.shape_1.setTransform(858.8,210.1);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#E2318B").s().p("AkpDIIAAmPIJTAAIAAGPg");
	this.shape_2.setTransform(801.4,210);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#009FE1").s().p("AkqDIIAAmPIJVAAIAAGPg");
	this.shape_3.setTransform(860.7,210);

	this.tfNum_Hundreds2 = new cjs.Text("00", "20px 'AMCE Basic'");
	this.tfNum_Hundreds2.name = "tfNum_Hundreds2";
	this.tfNum_Hundreds2.textAlign = "center";
	this.tfNum_Hundreds2.lineHeight = 22;
	this.tfNum_Hundreds2.lineWidth = 30;
	this.tfNum_Hundreds2.setTransform(740.1,401);

	this.pbMove_Hundreds = new lib.mcArrow();
	this.pbMove_Hundreds.setTransform(148.6,339.1,1,1,0,0,180);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f().s("#000000").ss(1,2,0,3).p("ATsFFMgnXAAAATslEMgnXAAA");
	this.shape_4.setTransform(896.9,416.5);

	this.tfNum_TenthsRemain = new cjs.Text("1", "16px 'AMCE Basic'", "#FF0000");
	this.tfNum_TenthsRemain.name = "tfNum_TenthsRemain";
	this.tfNum_TenthsRemain.textAlign = "center";
	this.tfNum_TenthsRemain.lineHeight = 18;
	this.tfNum_TenthsRemain.lineWidth = 14;
	this.tfNum_TenthsRemain.setTransform(927.8,239.5);

	this.tfNum_TensRemain = new cjs.Text("1", "16px 'AMCE Basic'", "#FF0000");
	this.tfNum_TensRemain.name = "tfNum_TensRemain";
	this.tfNum_TensRemain.textAlign = "center";
	this.tfNum_TensRemain.lineHeight = 18;
	this.tfNum_TensRemain.lineWidth = 14;
	this.tfNum_TensRemain.setTransform(797.2,239.5);

	this.tfNum_Tens2 = new cjs.Text("00", "20px 'AMCE Basic'");
	this.tfNum_Tens2.name = "tfNum_Tens2";
	this.tfNum_Tens2.textAlign = "center";
	this.tfNum_Tens2.lineHeight = 22;
	this.tfNum_Tens2.lineWidth = 30;
	this.tfNum_Tens2.setTransform(800.1,401);

	this.tfNum_Tens = new cjs.Text("00", "20px 'AMCE Basic G'");
	this.tfNum_Tens.name = "tfNum_Tens";
	this.tfNum_Tens.textAlign = "center";
	this.tfNum_Tens.lineHeight = 22;
	this.tfNum_Tens.lineWidth = 31;
	this.tfNum_Tens.setTransform(800,265.9);

	this.tfNum_Tens1 = new cjs.Text("00", "20px 'AMCE Basic G'");
	this.tfNum_Tens1.name = "tfNum_Tens1";
	this.tfNum_Tens1.textAlign = "center";
	this.tfNum_Tens1.lineHeight = 22;
	this.tfNum_Tens1.lineWidth = 31;
	this.tfNum_Tens1.setTransform(800,328.5);

	this.tfNum_Hundredths2 = new cjs.Text("00", "20px 'AMCE Basic'");
	this.tfNum_Hundredths2.name = "tfNum_Hundredths2";
	this.tfNum_Hundredths2.textAlign = "center";
	this.tfNum_Hundredths2.lineHeight = 22;
	this.tfNum_Hundredths2.lineWidth = 30;
	this.tfNum_Hundredths2.setTransform(989.1,401);

	this.tfNum_Hundredths = new cjs.Text("00", "20px 'AMCE Basic G'");
	this.tfNum_Hundredths.name = "tfNum_Hundredths";
	this.tfNum_Hundredths.textAlign = "center";
	this.tfNum_Hundredths.lineHeight = 22;
	this.tfNum_Hundredths.lineWidth = 31;
	this.tfNum_Hundredths.setTransform(988,265.9);

	this.tfNum_Hundredths1 = new cjs.Text("00", "20px 'AMCE Basic G'");
	this.tfNum_Hundredths1.name = "tfNum_Hundredths1";
	this.tfNum_Hundredths1.textAlign = "center";
	this.tfNum_Hundredths1.lineHeight = 22;
	this.tfNum_Hundredths1.lineWidth = 31;
	this.tfNum_Hundredths1.setTransform(988,328.5);

	this.pbAdd_Hundredths1 = new lib.pbPlus();
	this.pbAdd_Hundredths1.setTransform(627.8,359.6,1.19,1.19,0,0,0,16,16);

	this.pbGroup_Hundredths = new lib.mcArrow();
	this.pbGroup_Hundredths.setTransform(561.9,339.1,1,1,0,0,180);

	this.pbAdd_Tens1 = new lib.pbPlus();
	this.pbAdd_Tens1.setTransform(213.7,359.6,1.19,1.19,0,0,0,16,16);

	this.pbGroup_Ones = new lib.mcArrow();
	this.pbGroup_Ones.setTransform(285.2,339.1,1,1,0,0,180);

	this.tfNum_OnesRemain = new cjs.Text("1", "16px 'AMCE Basic'", "#FF0000");
	this.tfNum_OnesRemain.name = "tfNum_OnesRemain";
	this.tfNum_OnesRemain.textAlign = "center";
	this.tfNum_OnesRemain.lineHeight = 18;
	this.tfNum_OnesRemain.lineWidth = 14;
	this.tfNum_OnesRemain.setTransform(856,239.5);

	this.tfNum_Tenths2 = new cjs.Text("00", "20px 'AMCE Basic'");
	this.tfNum_Tenths2.name = "tfNum_Tenths2";
	this.tfNum_Tenths2.textAlign = "center";
	this.tfNum_Tenths2.lineHeight = 22;
	this.tfNum_Tenths2.lineWidth = 30;
	this.tfNum_Tenths2.setTransform(932.7,401);

	this.tfNum_Ones2 = new cjs.Text("00", "20px 'AMCE Basic'");
	this.tfNum_Ones2.name = "tfNum_Ones2";
	this.tfNum_Ones2.textAlign = "center";
	this.tfNum_Ones2.lineHeight = 22;
	this.tfNum_Ones2.lineWidth = 30;
	this.tfNum_Ones2.setTransform(858.9,401);

	this.mcClone = new lib.mcClone();
	this.mcClone.setTransform(813.1,111.3);

	this.tfNum_Tenths = new cjs.Text("00", "20px 'AMCE Basic G'");
	this.tfNum_Tenths.name = "tfNum_Tenths";
	this.tfNum_Tenths.textAlign = "center";
	this.tfNum_Tenths.lineHeight = 22;
	this.tfNum_Tenths.lineWidth = 31;
	this.tfNum_Tenths.setTransform(931.6,265.9);

	this.tfNum_Tenths1 = new cjs.Text("00", "20px 'AMCE Basic G'");
	this.tfNum_Tenths1.name = "tfNum_Tenths1";
	this.tfNum_Tenths1.textAlign = "center";
	this.tfNum_Tenths1.lineHeight = 22;
	this.tfNum_Tenths1.lineWidth = 31;
	this.tfNum_Tenths1.setTransform(931.6,328.5);

	this.tfNum_Ones = new cjs.Text("00", "20px 'AMCE Basic G'");
	this.tfNum_Ones.name = "tfNum_Ones";
	this.tfNum_Ones.textAlign = "center";
	this.tfNum_Ones.lineHeight = 22;
	this.tfNum_Ones.lineWidth = 31;
	this.tfNum_Ones.setTransform(858.8,265.9);

	this.tfNum_Ones1 = new cjs.Text("00", "20px 'AMCE Basic G'");
	this.tfNum_Ones1.name = "tfNum_Ones1";
	this.tfNum_Ones1.textAlign = "center";
	this.tfNum_Ones1.lineHeight = 22;
	this.tfNum_Ones1.lineWidth = 31;
	this.tfNum_Ones1.setTransform(858.8,328.5);

	this.pbAdd_Tenths1 = new lib.pbPlus();
	this.pbAdd_Tenths1.setTransform(492.9,359.6,1.19,1.19,0,0,0,16,16);

	this.pbAdd_Ones1 = new lib.pbPlus();
	this.pbAdd_Ones1.setTransform(348.2,359.6,1.19,1.19,0,0,0,16,16);

	this.pbGroup_Tenths = new lib.mcArrow();
	this.pbGroup_Tenths.setTransform(424.3,339.1,1,1,0,0,180);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("rgba(0,0,0,0.004)").s().p("AhiC+IAAl6IDGAAIAAF6gAgJBFIATAAIAAgYIgTAAg");
	this.shape_5.setTransform(896.2,285.9);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#000000").s().p("AgJAMIAAgXIATAAIAAAXg");
	this.shape_6.setTransform(896.2,291.7);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#000000").s().p("AgJAMIAAgXIATAAIAAAXg");
	this.shape_7.setTransform(896.2,352.2);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("rgba(0,0,0,0.004)").s().p("AhiC9IAAl5IDGAAIAAF5gAgJBGIATAAIAAgZIgTAAg");
	this.shape_8.setTransform(896.2,346.4);

	this.mcDecimal = new lib.mcDecimal();
	this.mcDecimal.setTransform(901.2,417,1,1,0,0,0,15,18);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#000000").s().p("AgJA2IAAgsIgsAAIAAgTIAsAAIAAgsIATAAIAAAsIAsAAIAAATIgsAAIAAAsg");
	this.shape_9.setTransform(702.7,347.8);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Aj2REMAAAgiHIHuAAMAAAAiHg");
	this.shape_10.setTransform(860.6,339.1);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#009FE1").s().p("AD4RdMAAAgiHInuAAMAAAAiHIgzAAMAAAgigQABgLAHgHQAHgHALAAIIgAAQAKAAAIAHQAGAHAAALMAAAAigg");
	this.shape_11.setTransform(860.6,336.6);

	this.instance = new lib.numboxlvl_grey("single",0);
	this.instance.setTransform(887.6,190.6,1.171,3.192,0,0,0,-1.5,0.1);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("Aj3RHMAAAgiNIHvAAMAAAAiNg");
	this.shape_12.setTransform(801.6,339.4);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#E2318B").s().p("AD4RgMAAAgiNInvAAMAAAAiNIgyAAMAAAgimQAAgLAIgHQAHgHAKAAIIhAAQAKAAAIAHQAHAHAAALMAAAAimg");
	this.shape_13.setTransform(801.6,336.9);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#FFFFFF").s().p("AA1BmQgGgGAAgLIAAhCIhdAAIAABCQAAALgGAGQgGAGgKAAQgKAAgGgGQgHgGAAgLIAAipQAAgLAHgGQAGgGAKAAQAKAAAGAGQAGAGAAALIAABAIBdAAIAAhAQAAgLAGgGQAGgGAKAAQAKAAAGAGQAGAGABALIAACpQgBALgGAGQgGAGgKAAQgKAAgGgGg");
	this.shape_14.setTransform(991.5,210);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#FFFFFF").s().p("AgPBlQgGgGAAgLIAAiVIghAAQgKAAgGgGQgEgHAAgIQAAgIAFgGQAGgGAJAAIBsAAQALAAAFAGQAFAGAAAIQAAAIgFAHQgEAGgMAAIggAAIAACVQAAALgGAGQgHAGgJAAQgIAAgHgGg");
	this.shape_15.setTransform(932.1,210.1);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#D36240").s().p("AkpDIIAAmPIJTAAIAAGPg");
	this.shape_16.setTransform(932.1,210);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#109C81").s().p("AkpDIIAAmPIJTAAIAAGPg");
	this.shape_17.setTransform(991.5,210);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#FFFFFF").s().p("Aj3RHMAAAgiNIHvAAMAAAAiNg");
	this.shape_18.setTransform(932.1,339.4);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#D36240").s().p("AD4RgMAAAgiNInvAAMAAAAiNIgyAAMAAAgimQAAgLAIgHQAHgHAKAAIIhAAQAKAAAIAHQAHAHAAALMAAAAimg");
	this.shape_19.setTransform(932.1,336.9);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#FFFFFF").s().p("Aj3RHMAAAgiNIHvAAMAAAAiNg");
	this.shape_20.setTransform(991.5,339.4);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#109C81").s().p("AD4RgMAAAgiNInvAAMAAAAiNIgyAAMAAAgimQAAgLAIgHQAHgHAKAAIIhAAQAKAAAIAHQAHAHAAALMAAAAimg");
	this.shape_21.setTransform(991.5,336.9);

	// addon
	this.mcPanel_Hundreds = new lib.mcLeftPanel();
	this.mcPanel_Hundreds.setTransform(11.2,130.3,0.502,0.713);

	this.mcDivider_Hundredths1 = new lib.mcDivider_Tenthcopy();
	this.mcDivider_Hundredths1.setTransform(621.3,354,0.576,1,0,0,0,113,0);

	this.mcPanel_Hundredths1 = new lib.mcLeftPanel();
	this.mcPanel_Hundredths1.setTransform(561.2,365.5,0.502,0.713);

	this.mcPanel_Hundredths = new lib.mcLeftPanel();
	this.mcPanel_Hundredths.setTransform(561.2,130.3,0.502,0.713);

	this.mcDivider_Tens1 = new lib.mcDivider_Ten();
	this.mcDivider_Tens1.setTransform(207.2,354,0.576,1,0,0,0,113,0);

	this.mcPanel_Tens1 = new lib.mcLeftPanel();
	this.mcPanel_Tens1.setTransform(147.1,365.5,0.502,0.713);

	this.mcPanel_Tens = new lib.mcLeftPanel();
	this.mcPanel_Tens.setTransform(147.1,130.3,0.502,0.713);

	this.mcDivider_Tenths1 = new lib.mcDivider_Tenth();
	this.mcDivider_Tenths1.setTransform(486.3,354,0.576,1,0,0,0,112.9,0);

	this.mcDivider_Ones1 = new lib.mcDivider_One();
	this.mcDivider_Ones1.setTransform(341.7,354,0.576,1,0,0,0,113,0);

	this.mcPanel_Tenths1 = new lib.mcLeftPanel();
	this.mcPanel_Tenths1.setTransform(426.3,365.5,0.502,0.713);

	this.mcPanel_Ones1 = new lib.mcLeftPanel();
	this.mcPanel_Ones1.setTransform(281.7,365.5,0.502,0.713);

	this.mcPanel_Tenths = new lib.mcLeftPanel();
	this.mcPanel_Tenths.setTransform(426.3,130.3,0.502,0.713);

	this.mcPanel_Ones = new lib.mcLeftPanel();
	this.mcPanel_Ones.setTransform(281.7,130.3,0.502,0.713);

	// Layer 2
	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f().s("#E2318B").ss(5,1,1).p("EAKKglDMAAABKHI0TAAMAAAhKHg");
	this.shape_22.setTransform(207.1,355.5);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("EgKIAlEMAAAhKHIURAAMAAABKHg");
	this.shape_23.setTransform(207.1,355.5);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f().s("#009FE1").ss(5,1,1).p("EAKKAlEI0TAAMAAAhKHIUTAAg");
	this.shape_24.setTransform(341.7,355.5);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("EgKIAlEMAAAhKHIURAAMAAABKHg");
	this.shape_25.setTransform(341.7,355.5);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f().s("#D36240").ss(5,1,1).p("EAKKglDMAAABKHI0SAAMAAAhKHg");
	this.shape_26.setTransform(486.3,355.5);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("EgKJAlEMAAAhKHIUTAAMAAABKHg");
	this.shape_27.setTransform(486.3,355.5);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f().s("#109C81").ss(5,1,1).p("EAKKAlEI0TAAMAAAhKHIUTAAg");
	this.shape_28.setTransform(621.2,355.5);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("EgKIAlEMAAAhKHIURAAMAAABKHg");
	this.shape_29.setTransform(621.2,355.5);

	this.instance_1 = new lib.numboxlvl_grey("single",0);
	this.instance_1.setTransform(405.7,116.8,1.737,5.913,0,0,0,-1.5,0.1);

	this.mcDisplay_Hundreds = new lib.mcDisplay_Thousands();
	this.mcDisplay_Hundreds.setTransform(-63.9,351.7,1,1,0,0,0,86.5,233.3);

	this.addChild(this.mcDisplay_Hundreds,this.instance_1,this.shape_29,this.shape_28,this.shape_27,this.shape_26,this.shape_25,this.shape_24,this.shape_23,this.shape_22,this.mcPanel_Ones,this.mcPanel_Tenths,this.mcPanel_Ones1,this.mcPanel_Tenths1,this.mcDivider_Ones1,this.mcDivider_Tenths1,this.mcPanel_Tens,this.mcPanel_Tens1,this.mcDivider_Tens1,this.mcPanel_Hundredths,this.mcPanel_Hundredths1,this.mcDivider_Hundredths1,this.mcPanel_Hundreds,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.instance,this.shape_11,this.shape_10,this.shape_9,this.mcDecimal,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.pbGroup_Tenths,this.pbAdd_Ones1,this.pbAdd_Tenths1,this.tfNum_Ones1,this.tfNum_Ones,this.tfNum_Tenths1,this.tfNum_Tenths,this.mcClone,this.tfNum_Ones2,this.tfNum_Tenths2,this.tfNum_OnesRemain,this.pbGroup_Ones,this.pbAdd_Tens1,this.pbGroup_Hundredths,this.pbAdd_Hundredths1,this.tfNum_Hundredths1,this.tfNum_Hundredths,this.tfNum_Hundredths2,this.tfNum_Tens1,this.tfNum_Tens,this.tfNum_Tens2,this.tfNum_TensRemain,this.tfNum_TenthsRemain,this.shape_4,this.pbMove_Hundreds,this.tfNum_Hundreds2,this.shape_3,this.shape_2,this.shape_1,this.shape,this.mcInstruction);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(511,383,1026,770);

})(lib = lib||{}, images = images||{}, createjs = createjs||{}, ss = ss||{});
var lib, images, createjs, ss;